### ISSUE TITLE
[Bug]: Error on startup

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#1]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

![Screenshot (309)](https://github.com/PikachuEXE/FreeTube/assets/73130443/6ecf480c-cc55-45ad-9aa2-e8d7c086d6bd)

### Expected Behavior

No errors?

### Issue Labels

only happens in developer mode

### FreeTube Version

Your FT version

### Operating System Version

Win10

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

Lol now i hate this template. Im just trying to dump info on u xD

### Nightly Build

- [x] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Probably fixed by https://github.com/FreeTubeApp/FreeTube/commit/c9680c1a1708173720f98a31c903b9be91df983d

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Yup dont see them anymore
