### ISSUE TITLE
[Feature Request]: Placement create new playlist button

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#10]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

This is just more of an suggestion

i thought the button looked off because it was placed at the right. 

### Proposed Solution

Put it somewhere else, i had no idea where at first but the logical way would be to place it to the left

Made a mockup
Does it look better to u?

![Screenshot (311)](https://github.com/PikachuEXE/FreeTube/assets/73130443/cd9e25f7-7cc1-4f61-8207-18d84bb150c9)

### Alternatives Considered

None.

### Issue Labels

visual improvement

**Comment by PikachuEXE** [comment]
Updated in https://github.com/FreeTubeApp/FreeTube/commit/e41210cbbca938f29d84584c88bde8a4681ea6f9
The original placement is from the old code not from me :3

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
What do you think of the changed placement. Does it look better to you or worse?

**Comment by PikachuEXE** [comment]
I think it's natural to see add new playlist button next to heading text
Though I am fine even when it's on the right
No preference for me, ask others :P

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@absidue @chunkyprogrammer what position of the `+` button do you prefer? Position as seen in https://github.com/PikachuEXE/FreeTube/issues/2 or as implemented here (see pic below)

![Capture](https://github.com/PikachuEXE/FreeTube/assets/73130443/d67c619a-1956-4fdd-91c6-eae905729e57)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as a think this is fine and that i overthink allot on if it looks good and natural
