### ISSUE TITLE
[Bug]: no videos thumbnail too big

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#11]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

When a playlist doesnt have videos the thumbnail is larger than all other thumbnails

https://github.com/PikachuEXE/FreeTube/assets/73130443/13e982cb-6fda-40b2-bfd3-86b13ac465d7

### Expected Behavior

All Thumbnails should be one size

### Issue Labels

inconsistent behavior, visual bug

### FreeTube Version

Yours

### Operating System Version

Mine

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Does FT have any fallback image now?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
To my knowledge FT doesn't have any fallback image

**Comment by PikachuEXE** [comment]
A lazy solution would be to force the aspect ratio
YT does not provide fallback image with 16/9 aspect ratio
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/40ba41ed-8499-400d-b80d-3ba7bb48f8f6)

Otherwise we need to create one for FT

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Forcing aspect ratio lgtm

**Comment by PikachuEXE** [comment]
Updated in https://github.com/FreeTubeApp/FreeTube/commit/5fd7f1f57632fb324e3a5bf85d3e2eac8e2cfef4
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/e2e38da9-85fd-4a96-a26e-7ad2c980a906)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/5fd13b0e-3864-442b-a1d8-7216bd7f8d57)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/55192fc4-78c8-4b45-9861-8a8660217c81)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM
