### ISSUE TITLE
[Bug]: Adding the same video to playlist isnt posible

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#12]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

The only reason i can think of that somebody wants to add the same video to a playlist is because they created a music playlist and would like to hear a song more than once in the list

https://github.com/PikachuEXE/FreeTube/assets/73130443/85bdd873-b26b-4884-951c-5137c7cb92d5

### Expected Behavior

I would like to add the same video to a playlist as often as i like

### Issue Labels

usability issue

### FreeTube Version

Latest

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Transition for https://github.com/PikachuEXE/FreeTube/issues/9 requires key to be unique and **non-changing**
Otherwise the transition would look like:

https://github.com/PikachuEXE/FreeTube/assets/1018543/889fe530-fb2f-41b2-9a75-0aa7510fa868

No idea how to implement a unique static key with duplicate video IDs yet

**Comment by PikachuEXE** [comment]
Implemented in https://github.com/FreeTubeApp/FreeTube/commit/5d3652481dfcf741adf61d6dc143310d841c1124

A lot of changes and relatively big chance to have bugs due to existing code (before change) all assume to have 1 video ID per playlist
Might miss some places

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM had 3 of the same vid in a playlist and moving/deleting wasnt giving me any bugs
