### ISSUE TITLE
[Feature Request]: Switch create new playlist and save button

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#13]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

IMO it would make more sense to have the save button in the middle and the create playlist button on the left side. IDK in my head that makes more sense.

![switch-save-create-buttons](https://github.com/PikachuEXE/FreeTube/assets/73130443/267037db-85fd-44dd-9bcb-dae67ff32f15)

### Proposed Solution

Switch save and create playlist buttons

### Alternatives Considered

None.

### Issue Labels

ease of use improvement, visual improvement

**Comment by PikachuEXE** [comment]
Something like this?
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/110e915b-0e85-4602-92e5-db9e5eb81fb4)

Creating playlist shouldn't be used that frequently to be on the left

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Srry i thought i had included the right screenshot. I think that the save button in the middle makes more sense not because of the frequency of being used but the natural resting position when the mouse is in use. But if u think that still doesnt make allot of sense feel free to close this :)

![Capture1](https://github.com/PikachuEXE/FreeTube/assets/73130443/96a49b0e-7a96-483a-89ce-0d2ccd14c6ca)

**Comment by PikachuEXE** [comment]
Leave for later
No idea yet

**Comment by PikachuEXE** [comment]
Now that the "copy playlist" is done by creating playlist than pressing save
I am fine with this idea
Done in https://github.com/PikachuEXE/FreeTube/commit/8ff279ebf829fba403a5f359294e3361b510f30c

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm
