### ISSUE TITLE
[Feature Request]: Move trash can icon to the right

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#14]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

So i understand the logical order of buttons here, add/remove/up/down but one missclick removes the video so i think they should be separated a bit. 

https://github.com/PikachuEXE/FreeTube/assets/73130443/e3e13555-0e66-41c8-9cdc-e2647be0467a

IDK if this makes sense to do though because u could make the argument that this misclick could also happen on the first and last video of the playlist

https://github.com/PikachuEXE/FreeTube/assets/73130443/9d6d4572-62a5-4a56-a8ae-5f434f35dc77

### Proposed Solution

Move trash icon to the right. 

### Alternatives Considered

None.

### Issue Labels

ease of use improvement

### Additional Information

Feel free to close the issue if u think it doesnt make sense. Im basically thinking out loud in these issues xD

**Comment by PikachuEXE** [comment]
Done in https://github.com/FreeTubeApp/FreeTube/commit/a65af47777c5bf608fef168ce55a6ccb1e550c8f

A safer UX thing might be have a button for "toggle allowing video removal mode"
Have a think

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I think this LGTM

The thing u suggested sounds to me more like a Parental Control. The kids have no way to edit the playlist (e.g: removing video's in playlist, removing playlist itself, moving videos, adding) but a read only mode state where they can go to a playlist and just watch the videos without messing the db file

Edit: essentially almost the same as the hide playlist function
