### ISSUE TITLE
[Feature Request]: Drag and drop videos in edit mode

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#15]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

When your playlist becomes very big it becomes annoying to move a video to a certain spot u like.

### Proposed Solution

Implement something like this in the playlist edit mode 

https://github.com/PikachuEXE/FreeTube/assets/73130443/c3af06b5-4381-4fe6-a8a8-7bd3c81582d2

### Alternatives Considered

None.

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by PikachuEXE** [comment]
Too much to implement as first version, maybe after playlist feature released and stable

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I'll leave this open so when it is release i can convert it to the main repo

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
migrated to https://github.com/FreeTubeApp/FreeTube/issues/4872
