### ISSUE TITLE
[Bug]: live videos can be added to playlist

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#16]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

IMO live videos shouldnt be added to the playlists. FT in some way recognizes it is a live video so when u hover over a thumbnail u cant add it to a playlist but when u go to the live video/stream u can add it to a playlist.

https://github.com/PikachuEXE/FreeTube/assets/73130443/0653d43b-4dac-4ca0-8650-44c2ca8bf3c2

### Expected Behavior

Remove add to playlist button on live streams/videos pages

### Issue Labels

inconsistent behavior

### FreeTube Version

Latest

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

So im not sure about one thing. Lets say channel X has a playlist that has live videos in it. Should the user be able to copy the list or not?

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
I think FT dev star button got the same behaviour/logic
I am just copying that from star button
So star button should be fixed first

**Comment by PikachuEXE** [comment]
More references:

### Video as List Item Behaviour
- https://github.com/FreeTubeApp/FreeTube/blame/development/src/renderer/components/ft-list-video/ft-list-video.vue#L48
- PrestonN committed on Feb 17, 2020

### Watch Page Behaviour
- https://github.com/FreeTubeApp/FreeTube/blame/development/src/renderer/components/watch-video-info/watch-video-info.vue#L85
- PrestonN committed on Jan 15, 2021
