### ISSUE TITLE
[Feature Request]: Switch Edit playlist and copy playlist button

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#17]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

IMO edit playlist button will be used more often then the copy playlist button. 

### Proposed Solution

Sort buttons based on priority of use

1. Edit playlist
2. Copy playlist
3. remove watched videos
4. delete playlist

So move the Edit button to be the first and copy as the second button

### Alternatives Considered

None.

### Issue Labels

ease of use improvement

### Additional Information

If u this isnt logical at all letme know

**Comment by PikachuEXE** [comment]
Done in https://github.com/FreeTubeApp/FreeTube/commit/733c3d8c0f0c5859520203a24dd7c7f07ae9741c

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm
