### ISSUE TITLE
[Feature Request]: Copy videos into other playlist

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#18]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

The copy playlist button gives u the option to copy the playlist with an altered name if u like. There is no way at the moment to copy videos of playlist into another playlist.

Lets say i created a playlist with some videos about repairing certain stuff. Now i see a channel that has a playlist about the same thing and all the videos in there a quite usefull to me. But i cant copy the videos of that playlist into my own created playlist. Now i have to manually add the videos to my playlist.

The same goes for 2 playlists created by me. I noticed that both playlist are about the same topic so i want to merge them. So i click the copy button but i cant select one of the playlist to copy them to

### Proposed Solution

Copy button should open a window like the one when u click on the + sign on a video thumbnail that gives u the option to create a playlist (current behavior) or copy the videos in one of your playlists

### Alternatives Considered

None.

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by PikachuEXE** [comment]
Implemented in https://github.com/FreeTubeApp/FreeTube/commit/467b151cf4225f2bd63578aedfccca374d2df324

Have a test

**Comment by PikachuEXE** [comment]
Also an improvement for copy playlist flow
https://github.com/FreeTubeApp/FreeTube/commit/6d49b10ae9e5aee33fcc38d5301355cad814827e

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Bug🐛

https://github.com/PikachuEXE/FreeTube/assets/73130443/5b5120a4-4458-4465-9998-e8de566ed055

**Comment by PikachuEXE** [comment]
Need some steps to reproduce it from empty playlists
I think I have fixed some bugs in https://github.com/FreeTubeApp/FreeTube/commit/a34774f46455d85eb9f51b3fa92353eceb948b7c already so not sure if you were testing with it
If so then I really need steps to reproduce

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sorry for not providing steps sometimes i think u have Wobbuffet's Telepathy ability. Either way i cant reproduce anymore so lgtm
