### ISSUE TITLE
[Bug]: Video counter doesnt always update

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#19]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Video number doesnt get updated on video remove

https://github.com/PikachuEXE/FreeTube/assets/73130443/9f2a3859-4801-4904-a30e-8673b0f0fce5

### Expected Behavior

Video counter should always update

### Issue Labels

inconsistent behavior, usability issue

### FreeTube Version

Latest

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Fixed in https://github.com/FreeTubeApp/FreeTube/commit/e61bc8d41aa2c2369fbd61a54656949b08e508c5

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm!
