### ISSUE TITLE
[Bug]: Previous saved videos are carried over into duplicate playlists

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#2]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

![Screenshot (310)](https://github.com/PikachuEXE/FreeTube/assets/73130443/f54cfcce-e911-46a3-ac15-348d7cc0f4b0)

### Expected Behavior

No duplicate playlists

### Issue Labels

usability issue

### FreeTube Version

Your FT version

### Operating System Version

Win10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Might be similar to #1 , fixed by https://github.com/FreeTubeApp/FreeTube/commit/c9680c1a1708173720f98a31c903b9be91df983d

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Not seeing duplicates anymore

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Reopening

Went back to latest nightly build saved some videos came back to your latest commit and saw this

![duplicate](https://github.com/PikachuEXE/FreeTube/assets/73130443/a38dd01a-e92c-4774-87e6-84fc4e3c2312)


Edit: just to make sure it was an actual duplicate i deleted one of them and it resulted in both getting removed

**Comment by PikachuEXE** [comment]
Need steps to reproduce ...

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
1. Go to nightly build
2. save some videos (u dont have to export)
3. quit ft
4. Now open FT in playlist branch
5. go to playlist and see duplicates

**Comment by PikachuEXE** [comment]
I added a video in `development` and switch back to playlist branch
I see no duplicate playlist, `Favorites` playlist contain correct number of videos and order

There was a line removed in https://github.com/FreeTubeApp/FreeTube/commit/d712bc8936bd8dacb6980a29be6cef362948a370
potentially making some playlists to be displayed twice

If you can still reproduce it with latest version I need an export (modified if needed) of playlist state before adding videos in `development` to check the properties of playlists

**Comment by PikachuEXE** [comment]
I can reproduce now ._.

**Comment by PikachuEXE** [comment]
Fixed in https://github.com/PikachuEXE/FreeTube/commit/d6e50d13b0f2c389423e62c79d44e3ba463f8769

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Nice lgtm
