### ISSUE TITLE
[Bug]: Saving in edit mode could be confusing 

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#20]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

So the Save and Cancel buttons are only for editing the Title and description of the playlist. Lets say the user is under the impression that a video stays in the playlist when they remove a video from the playlist and click on cancel. Even though we clearly say in edit mode that 

> video order updates and removals are saved immediately and cannot be canceled

I can understand that it could be confusing with those buttons there

https://github.com/PikachuEXE/FreeTube/assets/73130443/5aab1da6-42d8-4ab8-b5f8-e3e1c729ac43

### Expected Behavior

Hmm idk for sure, we can go 2 ways with this

1. Remove the buttons and save the description and title in realtime 
2. Keep the buttons but make it so that when the video order is changed or when a video is removed from the playlist the users can click on cancel to revert the changes or on save to confirm the changes

### Issue Labels

inconsistent behavior

### FreeTube Version

Latest

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
I think we can just have reorder buttons and trash buttons visible on hover in playlist view (for user playlists)

![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/81e74a83-4606-4d52-9757-d7b82d1e6704)

Updated in https://github.com/FreeTubeApp/FreeTube/commit/a90bea0075891163a8447104c1059e236ad9b1cd

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm
