### ISSUE TITLE
[Bug]: importing exported playlist doesnt work

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#21]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. I had 3 playlist; 1 playlist copied from the ltt channel with 20+ videos; favorites with 3 videos and watch later playlist with 3 videos
2. exported the playlist db
3. deleted copied playlist and deleted all videos in favorite/watch later playlist
4. tried to import playlist
5. errors

https://github.com/PikachuEXE/FreeTube/assets/73130443/976e0c46-fd9b-4d0d-aaca-09b9866e4683

### Expected Behavior

Import playlist without errors

### Issue Labels

data loss

### FreeTube Version

Latest

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Fixed some in https://github.com/FreeTubeApp/FreeTube/commit/fdf0b6dc944ee1dd4da5c36771156f5ea536af01

But the extra unknown key I am not sure if they should be "fixed" (seems like excessive data from somewhere I am not sure)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Importing old file (exported before default playlist removal was implemented) shows that i cant delete the playlist

https://github.com/PikachuEXE/FreeTube/assets/73130443/c26d24ce-c2c8-4358-a5cc-e2f263e8cc41

**Comment by PikachuEXE** [comment]
Hmm I guess I will make it ignore protected
Try reload the app and it should auto set it to not protected too

**Comment by PikachuEXE** [comment]
`protected` ignored in https://github.com/FreeTubeApp/FreeTube/commit/6ca4303752293d5bdde19977d91ca1d27727b3b5 (plus many other keys)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
almost there

So to find this i tested with 2 kinds of db files. 1 db is contained of 2 playlists i created and in those playlist are videos that i picked by random. Importing this went well.

https://github.com/PikachuEXE/FreeTube/assets/73130443/8dac1f15-89f6-4cbc-8244-e10ead352d6b

db nr 2 is contained of 2 playlists that i have copied from the ltt channel. So i went to a playlist on the channel pressed copy button -> did not modify playlist name -> copied the videos into that playlist -> exported db -> removed playlists -> imported db and saw that only the playlist were created but the videos werent in the playlists

https://github.com/PikachuEXE/FreeTube/assets/73130443/7813f793-9844-436b-b17d-501974fab0f0


Edit: 

> Importing old file (exported before default playlist removal was implemented) shows that i cant delete the playlist

Seems to be solved

**Comment by PikachuEXE** [comment]
It seems that some keys are absent when copying videos from online playlist
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/77adafe7-baee-4573-a789-6612cce6f032)

Any key should be ignored? I can try to fix the rest

Edit: These keys are added when import function added, see https://github.com/FreeTubeApp/FreeTube/blame/7822f7423e43f846df1bb2b5f7998dfe8a043198/src/renderer/components/data-settings/data-settings.js

**Comment by PikachuEXE** [comment]
Updated to ignore those keys
They are not used in `ft-list-video` (except `timeAdded`, which is generated later)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm!
