### ISSUE TITLE
[Bug]: Errors when going to playlist page

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#22]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Wanted to test all the new things u committed but i'm getting errors while trying to load the playlist page. I'll guess i hold off testing the rest until this is fixed.

https://github.com/PikachuEXE/FreeTube/assets/73130443/c634dff6-2bbb-4eb1-b70d-2135dc8278f1

### Expected Behavior

No errors and i would like to see my playlists again

### Issue Labels

content not loading

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/6d49b10ae9e5aee33fcc38d5301355cad814827e

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Could be corrupted playlist object saved (without `playlistName`)
Updated to ensure such property exists on reading

https://github.com/FreeTubeApp/FreeTube/commit/448913773c93272467dc90246c51ad31710d86e5

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Errors are gone but i do see this


https://github.com/PikachuEXE/FreeTube/assets/73130443/77f73fdc-9721-400c-9fc2-5cc3461964b9

**Comment by PikachuEXE** [comment]
I added code to ensure `playlistName` exists
I guess this is due to old playlist objects are using another property?
Let me check ._.

**Comment by PikachuEXE** [comment]
OK my exported playlist (from dev not this branch) has `playlistName`
So I need you to debug or find out whether the playlists are having playlist name in another property, or have no name at all
If former I need to make the code pick fallback values from that older property first

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I couldnt replicate this behavior anymore so i guess LGTM?
