### ISSUE TITLE
[Feature Request]: Change text fields on some places

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#23]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

1. This text was based on the legacy star method
![Capture](https://github.com/PikachuEXE/FreeTube/assets/73130443/5fd4eac8-55d2-4b37-a816-f93e29651ede)

2. It says edit playlist but it only edits the title and description
![Screenshot (315)](https://github.com/PikachuEXE/FreeTube/assets/73130443/b7ec098c-1efa-4b2b-8788-77b01ba24045)

### Proposed Solution

1. Make the text based on the revamped playlist page
2. Make text based on actual behavior 

### Alternatives Considered

None.

### Issue Labels

display more information to user, visual improvement

**Comment by PikachuEXE** [comment]
First one: `You have no playlist. Click on the create new playlist button to create a new one`?
No idea what to put on second one

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> First one: `You have no playlist. Click on the create new playlist button to create a new one`? 

Sounds good.

> No idea what to put on second one

`Edit Playlist Info`?

**Comment by PikachuEXE** [comment]
https://github.com/FreeTubeApp/FreeTube/commit/bb48262fd674873ba982f94c58ac44e545a49608

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm
