### ISSUE TITLE
[Bug]: Clicking fast on moving videos in playlist moves wrong video

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#24]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

So what im doing here is spamming the button that moves the video down and it results in another video coming up

https://github.com/PikachuEXE/FreeTube/assets/73130443/350ffa7e-a059-4160-8a84-a0f77f16de5b

### Expected Behavior

This is what i would've expected to happen. I'm basically rotating between 2 videos

https://github.com/PikachuEXE/FreeTube/assets/73130443/91db8cad-e72e-4eb7-91f9-2c19cc24d021

### Issue Labels

inconsistent behavior

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/fdf0b6dc944ee1dd4da5c36771156f5ea536af01

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
No idea how to disable link response during animation...
Thoughts?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Maybe add a minor delay to the buttons. So if u click on a move button u cant click on the move buttons immediately after that? Or make the buttons not visible in that delay period?

**Comment by PikachuEXE** [comment]
https://github.com/FreeTubeApp/FreeTube/commit/5feb3b1d65a3c83e03bea5e7f503629ecae3ea40

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM but i see this red thing when clicking on the buttons

https://github.com/PikachuEXE/FreeTube/assets/73130443/7edba589-7b60-4465-b9b7-47a0e85c24ef

**Comment by PikachuEXE** [comment]
It shouldn't work lol

I forgot to revert code changes for testing only
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/8c69ccf8-cfcd-43a7-8ee1-f1e16b10bd89)

Now fixed - https://github.com/PikachuEXE/FreeTube/commit/2cd24639dee9b9149ac2a9b7ffea78f6e4ab3fec

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Still happens :( 

https://github.com/PikachuEXE/FreeTube/assets/73130443/29e1700a-77a5-4ea5-966b-9deeccd4630b

**Comment by PikachuEXE** [comment]
Should be really fixed now https://github.com/PikachuEXE/FreeTube/commit/c432017ad8f690046187420e3d8dfc4a771787b1
I updated transition to 2s to test:

https://github.com/PikachuEXE/FreeTube/assets/1018543/8d4b9580-31c3-42c6-a98f-75fb6fcaae15

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I get an error when i click fast


https://github.com/PikachuEXE/FreeTube/assets/73130443/c1249f98-d891-479c-bd64-e2e51799ad39

Edit: original issue is indeed fixed now

**Comment by PikachuEXE** [comment]
._.
How to prevent link click!?

**Comment by PikachuEXE** [comment]
Done in https://github.com/PikachuEXE/FreeTube/commit/a5292ec145f4629886240b65481b841e9359f309

TIL `pointer-events`
https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM!
