### ISSUE TITLE
[Feature Request]: Parental Control Read/Play only playlist mode

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#25]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

U have kids and u want them to watch the playlists u created for them but u dont want them to modify the db in any way

### Proposed Solution

This feature is almost the same as the 'Hide Playlist' Distraction Free Setting but allows the child to go to the playlist tab and ONLY watch the videos in the playlist. Just like they would if they go to a channel and select a playlist to watch.

### Alternatives Considered

None.

### Issue Labels

new feature

**Comment by PikachuEXE** [comment]
Won't implement in first version

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
migrated to main repo https://github.com/FreeTubeApp/FreeTube/issues/4871
