### ISSUE TITLE
[Bug]: Cant select playlist to add video because playlist title too big

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#26]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Made title big and now i cant add video to playlist. Scrolling down doesnt bring me to the buttons

https://github.com/PikachuEXE/FreeTube/assets/73130443/add4d3bd-6396-43cd-9596-2eb7d76ac94a

### Expected Behavior

I would like to see the buttons when i scroll down

### Issue Labels

inconsistent behavior, usability issue, visual bug

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/fdf0b6dc944ee1dd4da5c36771156f5ea536af01

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
https://github.com/FreeTubeApp/FreeTube/commit/dd1ce2ea92045b6a6116df6e1a7e658ca61203c4

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm
