### ISSUE TITLE
[Bug]: Progress bar showing in delete playlist menu

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#27]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Have a playlist with 2 videos
2. 2nd video in the list should be watch almost completely 
3. delete playlist
4. see that the watch time shows on top of the delete playlist menu

Maybe related to https://github.com/FreeTubeApp/FreeTube/issues/3288

https://github.com/PikachuEXE/FreeTube/assets/73130443/395b65c9-e658-464a-9954-29444d04890e

### Expected Behavior

Watch progress time isn't shown on the delete playlist menu

### Issue Labels

visual bug

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/cb2aa490e2dc672a3f6c9fee8dfa2e6148c6cb2e

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
I fixed it partially but I don't have progress bar enabled then in https://github.com/FreeTubeApp/FreeTube/commit/25c647e94003797631628229a0348a11d5b00d36

z-index raised again in https://github.com/FreeTubeApp/FreeTube/commit/0d000b9f338e6cdd7003f8668b0585143c206391

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm
