### ISSUE TITLE
[Bug]: Wording Watch Later playlist wrong when importing legacy db

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#28]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Prerequisite: Have a legacy playlist db 

1. Open FT
2. Go to playlist and make sure there are no playlists
3. Import legacy playlist
4. Go to playlist 
5. See that WatchLater playlist is added automatically but is spelled wrong

https://github.com/PikachuEXE/FreeTube/assets/73130443/a0b3488b-6bf3-4079-a990-dac989f5b0c1

### Expected Behavior

WatchLater should be spelled Watch Later

### Issue Labels

text/string issue

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/cb2aa490e2dc672a3f6c9fee8dfa2e6148c6cb2e

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

Maybe talk about when we want to include the default playlists and when not. I have the feeling that it isnt very clear when to include them but that could also be my slowpoke head

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Coz there is a hidden default playlist with name `WatchLater`
But then I doubt if we should add specific code to reject such playlist
It's a one time issue from `one default playlist plus one hidden playlist` to multiple playlists

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah okay then im fine with it.


> Maybe talk about when we want to include the default playlists and when not. I have the feeling that it isnt very clear when to include them but that could also be my slowpoke head

Could u maybe explain to me in what usecases the default playlists gets added and when they are not

**Comment by PikachuEXE** [comment]
On this branch: No playlist = add default playlists
