### ISSUE TITLE
[Bug]: Hover on Live video thumbnail doesnt show add to playlist button

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#29]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Search for live
2. hover over live videos
3. See that the add to playlist button isn't there
4. Click on the video
5. U can add the video from the playlist page

https://github.com/PikachuEXE/FreeTube/assets/73130443/0653d43b-4dac-4ca0-8650-44c2ca8bf3c2

### Expected Behavior

Users should be able to save the video from any page when hovering the live video thumbnail

### Issue Labels

inconsistent behavior

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/34fb37a492ba33071c6857554d498f1ce713a8a1

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
To be done after https://github.com/FreeTubeApp/FreeTube/pull/3598 merged

**Comment by PikachuEXE** [comment]
Done in https://github.com/PikachuEXE/FreeTube/commit/51c1bf29aee8e5de35807c5ff871fe9b10d28ce0 after rebase

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm
