### ISSUE TITLE
[Feature Request]: Icons on thumbnail only visible on hover

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#3]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

![Capture](https://github.com/PikachuEXE/FreeTube/assets/73130443/59347afc-91ea-48d3-a52b-a63e76135c39)

### Proposed Solution

https://github.com/PikachuEXE/FreeTube/assets/73130443/c2fdb3de-46ea-4282-8e04-1c8cb0d8731f

### Alternatives Considered

None.

### Issue Labels

visual improvement

**Comment by PikachuEXE** [comment]
Done in https://github.com/FreeTubeApp/FreeTube/commit/cb6f840e4ac26542837de322eed340c3c5c544e1

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM, the only thing im not sure about is if we should show the add to playlist button by default if the edit mode is enabled. What do you think?


https://github.com/PikachuEXE/FreeTube/assets/73130443/f7349db2-dc71-44a9-9b1b-b3b04daaaed0

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is implemented LGTM
