### ISSUE TITLE
[Bug]: Playlist takes forever to load

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#31]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Sometimes Local saved or Normal playlists takes forever to load. It never shows the content. Maybe somewhat related to https://github.com/FreeTubeApp/FreeTube/issues/3349 idk searching just works fine

https://github.com/PikachuEXE/FreeTube/assets/73130443/33cdb65b-c726-4c9b-abdc-0923d52e5f23

### Expected Behavior

Show me the playlist pls

### Issue Labels

content not loading

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/34fb37a492ba33071c6857554d498f1ce713a8a1

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Unless it can be reproduce with some steps
Otherwise I can't even debug :S

**Comment by PikachuEXE** [comment]
Seems can be reproduced by removing all playlists, then reopen the app and click on any playlist

**Comment by PikachuEXE** [comment]
Fixed in https://github.com/PikachuEXE/FreeTube/commit/85be6834420f6a4655a1d980516eaab109277c15

BTW added remove all playlists buttons in https://github.com/PikachuEXE/FreeTube/commit/cc0cb934901c981348bbe2273b9c322caf932427

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm
