### ISSUE TITLE
[Bug]: Watch page throw error when visiting history entry with deleted user playlist ID

### ISSUE THREAD

**Issue by PikachuEXE** [PikachuEXE/FreeTube#32]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

- Find random video, add to a new user playlist
- View the video in that user playlist
- Delete the user playlist
- Visit History, view the video again

### Expected Behavior

No error, just like viewing the video without playlist (since the playlist is gone)

### Issue Labels

usability issue

### FreeTube Version

bbe1593b02ceb15445870775eb889ab5d58b659d

### Operating System Version

MacOS

### Installation Method

.dmg

### Primary API used

Local API

### Additional Information

Add feature to remember video history with last viewed playlist when enabled: https://github.com/FreeTubeApp/FreeTube/pull/3006

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Fixed in https://github.com/PikachuEXE/FreeTube/commit/5ccbec609f02a67606bd2e57f20eb3cb9aa195d1
Better get someone else to test though (Though I tested once)

@efb4f5ff-1298-471a-8973-3d47447115dc ~

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is also fixed!

**Comment by PikachuEXE** [comment]
Well closing then
