### ISSUE TITLE
[Bug]: Share button return URL with user playlist ID

### ISSUE THREAD

**Issue by PikachuEXE** [PikachuEXE/FreeTube#33]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

- Add a video to a user playlist
- Watch it via user playlist / view user playlist (with video list)
- Use share button to copy YT/Invidious video URL (not channel)

### Expected Behavior

Video URLs for sharing to NOT include playlist ID from any user playlist

### Issue Labels

usability issue

### FreeTube Version

5ccbec609f02a67606bd2e57f20eb3cb9aa195d1

### Operating System Version

MacOS

### Installation Method

.dmg

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Fixed in https://github.com/PikachuEXE/FreeTube/commit/1e42a598f6b4e00be9132f270d8df165ca87471e
Tested both watch page & playlist view

@efb4f5ff-1298-471a-8973-3d47447115dc Please test too when available :)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is indeed fixed!

**Comment by PikachuEXE** [comment]
Well closing then
