### ISSUE TITLE
[Bug]: Error when copying playlists

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#34]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Not sure what happened here but i copied these 3 playlist and got this error

https://github.com/PikachuEXE/FreeTube/assets/73130443/4ab3e580-97c7-4d49-9a24-c2c185ecd0da

### Expected Behavior

No error?

### Issue Labels

inconsistent behavior

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/1e42a598f6b4e00be9132f270d8df165ca87471e

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Not when copied, but when viewing some playlists
e.g. 
https://youtube.com/playlist?list=PLbWPaa_yYpY3Rz0U1SxqDX_LoMmvK_XUE

I found another with another error
https://youtube.com/playlist?list=PLiTZRn7zC_D4TZD3sPdbkKcLtNJWoOonA

Upper: `PLbWPaa_yYpY3Rz0U1SxqDX_LoMmvK_XUE`
Lower: `PLiTZRn7zC_D4TZD3sPdbkKcLtNJWoOonA`
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/fcc793d8-f6eb-4b9d-baea-a7b6337ee394)

**Comment by PikachuEXE** [comment]
Fixed duplicate key in https://github.com/PikachuEXE/FreeTube/commit/416a7a81f0bbed32f0b46907598c16dafc324fb8

**Comment by PikachuEXE** [comment]
Fixed missing key in https://github.com/PikachuEXE/FreeTube/commit/4fecf0f728c8e53f5807674cad088a9d12a09e95
But now the load more button has animation lol

**Comment by PikachuEXE** [comment]
Unnecessary animation fixed in https://github.com/PikachuEXE/FreeTube/commit/2992b4b74031109171f1dcd163bc76636aab4177

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Got this error when navigating to https://youtube.com/playlist?list=PLbWPaa_yYpY3Rz0U1SxqDX_LoMmvK_XUE

![Capture](https://github.com/PikachuEXE/FreeTube/assets/73130443/ab05fa9b-4a1f-4105-9dd6-4b081e88eaad)


Edit: i got it only once and dont get it anymore so not sure what happened

**Comment by PikachuEXE** [comment]
Cannot reproduce
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/9694908f-b950-48e9-87e8-0f65f0dd2f1a)

I am using a5292ec145f4629886240b65481b841e9359f309

**Comment by PikachuEXE** [comment]
`infoSource` can only be set to `user` in `parseUserPlaylist` in `src/renderer/views/Playlist/Playlist.js`
It's called only when `this.selectedUserPlaylist != null`
Even with user playlist present with that playlist ID both components should have returned the same result

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hmm cant reproduce this anymore so i think i maybe messed something up. Anyway closing this as everything is addressed
