### ISSUE TITLE
[Feature Request]: Add toast message when all playlists are removed by the privacy setting

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#35]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

When u click yes when u confirm to delete all playlists there is no toast message confirming that the playlists are removed. Ofcourse the user can go to the playlist tab to check for them self.

### Proposed Solution

This is just a nice to have. Add toast message that confirms that all the playlists are removed.

### Alternatives Considered

None.

### Issue Labels

display more information to user

**Comment by PikachuEXE** [comment]
Done in https://github.com/PikachuEXE/FreeTube/commit/9a3b302bbefd780c9f85233ec15939a0113b4d36

I was copying `handleRemoveSubscriptions` and that one has no message

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm
