### ISSUE TITLE
[Feature Request]: Remove Privacy setting `Remove all playlist` when distraction free settings `hide playlists` is enabled

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#36]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

In https://github.com/PikachuEXE/FreeTube/issues/4 we implemented to disable everything that could manipulate the db file when `hide playlist` is enabled. When this is enabled u can still manipulate the db by deleting every playlist in the privacy setting

### Proposed Solution

Remove Privacy setting `Remove all playlist` when distraction free settings `hide playlists` is enabled

### Alternatives Considered

None.

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by PikachuEXE** [comment]
I don't think that's what that "distraction free" option is for
If the intention is to prevent DB manipulation, use password for settings
As a privacy centric app I don't see a reason to hide any button to nuke the local data

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You're right, it would maybe fit in more with https://github.com/PikachuEXE/FreeTube/issues/25
