### ISSUE TITLE
[Feature Request]: Copying remote playlist with > 100 videos improvement

### ISSUE THREAD

**Issue by PikachuEXE** [PikachuEXE/FreeTube#37]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Copying remote playlist with > 100 videos, like https://youtube.com/playlist?list=PL8mG-RkN2uTy5zBlQstuTnIUEQPe5rDHx
Requires manually loading all videos first

If copied without all videos loaded (e.g. only first 100 videos), only those videos will be added to user playlist

### Proposed Solution

NO IDEA

### Alternatives Considered

Manually loading all videos lol

### Issue Labels

ease of use improvement, improvement to existing feature

### Additional Information

Copying user/local playlist is fine since all videos are displayed

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Maybe something like this?

If click on copy playlist button should execute the load more button if its there

**Comment by PikachuEXE** [comment]
That does not solve the problem completely
Consider playlist with > 200 videos :)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
If click copy playlist button execute the load more button if its there and check if it is still there after execution?

 Edit: edge case huge playlist https://www.youtube.com/playlist?list=PLLGmt3bXA_93pvHgKm7dbEvW410pDFKKl

**Comment by PikachuEXE** [comment]
Too much to do with error handling and stuff just for a copy button, I don't think it's a good UX

**Comment by PikachuEXE** [comment]
Implement a toast message in https://github.com/PikachuEXE/FreeTube/commit/bd9ff58d425bcd66e105e978a06634cbd044324d
But user can still click to copy the playlist anyway

![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/2911869d-31d7-4761-a1f3-ed4fee6334b0)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
That's nicely solved, LGTM.
