### ISSUE TITLE
[Bug]: New playlist does not appear in other windows

### ISSUE THREAD

**Issue by PikachuEXE** [PikachuEXE/FreeTube#38]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

- Open >=2 windows
- Pick a random window to create a new playlist via button in user playlist page or plus button on video
- Switch to another window to view user playlist page and/or add video to playlist prompt

### Expected Behavior

New playlist should be visible in all other windows

### Issue Labels

usability issue

### FreeTube Version

arrrrr

### Operating System Version

Windows 10

### Installation Method

Portable

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Fixed in https://github.com/PikachuEXE/FreeTube/commit/a08126679c965139458450a0011a3cce62b3cc89

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Lgtm!
