### ISSUE TITLE
[Feature Request]: Mark new playlist selected after created in add video to playlist prompt

### ISSUE THREAD

**Issue by PikachuEXE** [PikachuEXE/FreeTube#39]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

- Open add video to playlist prompt
- Click Add new playlist
- Create a new playlist
- New playlist not selected

### Proposed Solution

Make new playlist selected (and actually would have videos added when `Save` click not just visual effect lol)

If multiple playlists created **via the button on prompt**, make them all selected after creation

### Alternatives Considered

Extra click after new playlist created

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by PikachuEXE** [comment]
Done in https://github.com/PikachuEXE/FreeTube/commit/6ec711cef0d6a0419b10415de6793db8c4646049

To test:
- Open add video to playlist prompt
- Create 1 playlist, ensure it's auto selected
- Unselect the auto selected playlist
- Create 1 playlist again
- Ensure the new playlist is auto selected, but not the first created playlist (which is manually unselected)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM!
