### ISSUE TITLE
[Feature Request]: Disable playlist features when `Hide playlist` is enabled

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#4]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

For whatever reason i decide to hide the playlists but i can still interact with it in all sorts of ways

https://github.com/PikachuEXE/FreeTube/assets/73130443/a4fc073f-25f7-46ff-b392-1e619c3f22cc

### Proposed Solution

All interractions that manipulate the playlist db file should also be disabled

### Alternatives Considered

None.

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by PikachuEXE** [comment]
Updated in https://github.com/FreeTubeApp/FreeTube/commit/6fecdea4af48b582cc49092ad1435c40b62e7b2c

Hidden star video button, add to playlist button, copy button on playlist

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm!
