### ISSUE TITLE
[Feature Request]: Improve accessibility of thumbnail add to playlist button

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#41]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I must hover over a thumbnail to tab to the add to playlist button

https://github.com/PikachuEXE/FreeTube/assets/73130443/e002e46f-28b7-43b6-8b3d-4c2692212b29

### Proposed Solution

It would be nice if i could tab to that button without needing to hover with my cursor over the thumbnail

### Alternatives Considered

None.

### Issue Labels

ease of use improvement

**Comment by PikachuEXE** [comment]
Like this?
Still need to click on the prompt first though

https://github.com/PikachuEXE/FreeTube/assets/1018543/63796c33-121c-4d3a-bfd2-c85f4729d35f

**Comment by PikachuEXE** [comment]
Anyway committed in https://github.com/PikachuEXE/FreeTube/commit/78e7d663231ebfb0f79eab7f39ae3554555b0a41

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah i wasnt clear enough on this one. The only way to add a video to a playlist is to hover over a thumbnail to see the button so u can click on it. What i am showing u in the video is that i use tab to try to go the that add button but that doesnt work. It only works with tabbing if my cursor hovers over the thumbnail.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Like this? Still need to click on the prompt first though
> Screen.Recording.2023-06-07.at.09.34.51.mov

This is also a nice improvement over the previous implementation. Is it possible to make it that u dont have to click the prompt or is that just how it works?

**Comment by PikachuEXE** [comment]
> This is also a nice improvement over the previous implementation. Is it possible to make it that u dont have to click the prompt or is that just how it works?

Even with prompt tabindex set to 0, due to focus being on plus button, you will need to tab through the rest of videos before it goes into the prompt
That's what I mean by `Still need to click on the prompt first`

**Comment by PikachuEXE** [comment]
I left 3 replies starting https://github.com/PikachuEXE/FreeTube/issues/42#issuecomment-1581705532 in a wrong thread lol

**Comment by PikachuEXE** [comment]
I make a change in https://github.com/PikachuEXE/FreeTube/commit/1655d3a149c25dc59550fe6f8567a36fd4eac2aa

Update add video to playlist prompt to focus on search input on shown

Not sure if that's good enough, test it

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This implementation is exactly what i was looking for. I have some other accessibility suggestions and will place them all in one big issue. This particular issue is solved, lgtm!
