### ISSUE TITLE
Question: Playlist thumbnail buttons not shown by default in local playlist

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#42]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I'm not sure anymore but i thought that we implemented to show the buttons on thumbnails by default if you are in your local playlist

https://github.com/PikachuEXE/FreeTube/assets/73130443/5547fdea-e6f5-4a5b-b864-643d3710d2a4

### Proposed Solution

Make them visible again by default if you are in your local playlist?

I can remember we discussed this somewhere but cant find it

### Alternatives Considered

None.

### Issue Labels

ease of use improvement

**Comment by PikachuEXE** [comment]
You said OK in 
https://github.com/PikachuEXE/FreeTube/issues/20#issuecomment-1560345029
LOL?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> I think we can just have reorder buttons and trash buttons visible on hover in playlist view (for user playlists)

LOL SMH i clearly didnt read the visible on hover part. Umm yeah so... IMO it would be logical to show the buttons by default instead of hover in the playlist view. The reason i asked for the add to playlist button to be there on hover is because there were so many people in the main repo complaining about it (which i do kind of understand, i doesnt look that "clean") but in the playlist view i think the user wants to see everything they can do in a glance instead of figuring out that u need to hover to interact with the playlist.

**Comment by PikachuEXE** [comment]
b35db8f3e0731f5de3ee7f65ee760ab607dff95a
Add to playlist button still only visible on hover

![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/40673129-c1b1-448f-92ff-c0defdcd1c52)

**Comment by PikachuEXE** [comment]
Problem is that to make it visible on focus, there must be another another element to be focused on before that plus button
Either we move it the end (which is weird) or make something focusable in the front (which is always visible)

**Comment by PikachuEXE** [comment]
I tried making `thumbnailLink` focusable (tabindex was -1) and it works
But it doesn't have to  be that element
Though I have no idea what to pick
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/d05adbc1-506d-4084-a3ac-e6e811d5ff18)

**Comment by PikachuEXE** [comment]
Try it in https://github.com/PikachuEXE/FreeTube/commit/6c5b30f9494c1b5b95c7656627c220208b8cba05

**Comment by PikachuEXE** [comment]
Wrong thread for last 3 replies LOL

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Would like the add to playlist button (`+`) also to be visible by default in the playlist view.

**Comment by PikachuEXE** [comment]
Done in https://github.com/PikachuEXE/FreeTube/commit/1700624db9ee257596a5474f684d763a350d8c1d

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm
