### ISSUE TITLE
[Feature Request]: Suggestion to improve Accessibility 

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#43]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

1. If i tab through the add to playlist menu it doesn't cycle through the playlists to so the user can never select them.

https://github.com/PikachuEXE/FreeTube/assets/73130443/d6cba740-8c52-4461-8a49-0fefb619791f

2. Here i have to tab through all my playlists before i can give my new playlist a name. I know i have only 2 playlists here but image if you have 100+ playlists.

https://github.com/PikachuEXE/FreeTube/assets/73130443/5744e723-ac74-4ad5-8c55-730b17eecafc

3. I have to tab through every element to get to edit playlist name/description

https://github.com/PikachuEXE/FreeTube/assets/73130443/4461168e-f482-4d65-9809-e14672de12cd

4. I have to tab through every element to get to name and save my new playlist

https://github.com/PikachuEXE/FreeTube/assets/73130443/e0b6b7a1-050a-4751-94fc-91e2b58a63b4

4.1. Expansion on 4, i can cancel the prompt where i need to select a playlist to add my videos to but i can still create a playlist

https://github.com/PikachuEXE/FreeTube/assets/73130443/72770bd3-78a6-43c7-8d7b-752788ae92ed

5. When i press cancel i and press tab again i have to cycle through every element to get back to the playlist prompt

https://github.com/PikachuEXE/FreeTube/assets/73130443/47714b67-ddfd-4873-8eaa-a10721cba054

6. When i add playlist it doesnt come back to the playlist prompt

https://github.com/PikachuEXE/FreeTube/assets/73130443/2bace1ae-05b4-47ca-919e-8f3befb2c53e

7. Clicking on copy button brings me to prompt but if i cancel and press tab i'm not on the copy button anymore

https://github.com/PikachuEXE/FreeTube/assets/73130443/c6c30eb6-9065-4ffd-a53c-f836054ef863

8. add or cancel playlist prompt does not bring focus back to thumbnail

https://github.com/PikachuEXE/FreeTube/assets/73130443/a60f9970-db07-4226-81f4-d2fd422841aa

9. when i cancel or save my playlist it doesnt take me back to the add to playlist button under the video player

https://github.com/PikachuEXE/FreeTube/assets/73130443/9460240b-e4da-45be-8ddd-74d865c755a4

10. when i cancel or save my video it doesnt take me back to the add to playlist button on the thumbnail

https://github.com/PikachuEXE/FreeTube/assets/73130443/30f0b771-d105-4c2b-bbd7-58125c060ecd

11. clicking cancel on deleting playlist prompt doesnt take focus back to delete playlist button

https://github.com/PikachuEXE/FreeTube/assets/73130443/60e2d835-1314-4194-aa67-90b73aa0cecd

12. clicking cancel or save on removing watched video prompt doesnt take focus back on remove watched video button

https://github.com/PikachuEXE/FreeTube/assets/73130443/0adf2c2a-a09c-470c-af56-a81d4811f4d4

13. clicking cancel or save on playlist prompt doesnt take me back to copy button

https://github.com/PikachuEXE/FreeTube/assets/73130443/77fab3fe-eb03-4d21-8ab0-4dd5fb676638

14. when saving a video to playlist doesnt give focus back to the thumbnail

https://github.com/PikachuEXE/FreeTube/assets/73130443/8b627cb2-c4f0-4968-a03e-970efd127c36

15. when cancel add video to playlist prompt it doesnt give focus back to the thumbnail

https://github.com/PikachuEXE/FreeTube/assets/73130443/dd904931-9e1a-4dc1-a81b-393d0f52f63c

### Proposed Solution

- [x] 1. Would like to cycle through the playlists so i can select one of them in order to add my videos to it
- [x] 2. Would like the focus to be on the input field after clicking on that button so i dont have to cycle through all my playlists to get to the input field
- [x] 3. Would like the focus to be on the input fields instead of having to cycle through every element
- [x] 4. Would like the focus to be on the input field so i can give my new playlist a name
- [ ] 4.1. IDK if there is a solution to this i just wanted to mention it and to get your thoughts on it
- [x] 5. Would like the focus to be on the playlist prompt (not sure where maybe where it left off on the create new playlist button)
- [x] 6. Would like the focus to be on the playlist prompt (not sure where maybe where it left off on the create new playlist button)
- [x] 7. Would like the focus to be on the copy playlist button when i cancel/save playlist prompt
- [x] 8. Bring focus back to thumbnail when i cancel/save prompt
- [x] 9. take me back to the add to playlist button under the video player when i press tab
- [x] 10. take me back to the add to playlist button on the thumbnail
- [x] 11. take focus back on delete button
- [x] 12. take foucs back on remove button
- [x] 13. take focus back on copy playlist button
- [x] 14. focus on thumbnail again
- [x] 15. focus on thumbnail again

### Alternatives Considered

None.

### Issue Labels

ease of use improvement

**Comment by PikachuEXE** [comment]
Done changes for 1&2 in https://github.com/PikachuEXE/FreeTube/commit/b6b60f50e28bee575c501616833091b87d69fc3e

Test especially with both prompt visible

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Tested 1&2 and LGTM

Edit: 4 is also fixed probably by nr 2.

2nd Edit: i think i have every part of the UI listed now, tried to be thorough with it

**Comment by PikachuEXE** [comment]
Is there any existing prompt that would refocus on previously focused element on dismiss?
If not then those might not be implemented soon

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hmm idk will test later today!

Also @chunkyprogrammer does these suggestions even make sense from an accessibility standpoint? I mean to me it does and i think it works like this in the browser (am not sure about that though)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PikachuEXE its very inconsistent how things are handled rn 

In the privacy settings menu click Clear search cache or remove watch history -> use tab and press enter on no to cancel the prompt -> press tab again and see that the hamburger menu is on focus just like u saw in some of the screenrecordings

In the privacy settings menu click Remove all subscriptions / profiles -> tab to no and press enter -> press tab and see that focus is on the privacy settings tab

Not sure if this is the same because it opens a OS prompt for importing/exporting but in the data settings when u click on one of the options -> and cancel that prompt the button where u initially clicked on is still on focus. 

There is on exclusion to this and that is the export Subscriptions setting because that does bring up a FT prompt. When u cancel that prompt and hit tab again the Data settings tab is in focus

**Comment by PikachuEXE** [comment]
Let's move non playlist related stuff into another issue (probably in main repo)
Otherwise this takes forever to finish playlist feature =_=

**Comment by PikachuEXE** [comment]
(3) should be fixed in https://github.com/PikachuEXE/FreeTube/commit/a624a85b12a7b467c2b8eb7ab06b77d0f5c26de8

**Comment by PikachuEXE** [comment]
> There is on exclusion to this and that is the export Subscriptions setting because that does bring up a FT prompt. When u cancel that prompt and hit tab again the Data settings tab is in focus

The reason is that the prompt element is rooted in that section, when prompt is closed = destroyed, the next focus target would still be picked from the last parent (I guess)

But this is not true with "global" prompt where the prompt element is rooted in "app"

To be able to auto focus on last focused element after closing a "global" prompt is another thing to do but should not be part of the playlist feature implementation

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can confirm 3 is fixed

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
if we cut out non related playlist stuff then i think we should only do 5/6/11/12

**Comment by PikachuEXE** [comment]
Done a change in https://github.com/PikachuEXE/FreeTube/commit/e2b1f4f0f03b876040f6a39c5e81e08192612c8f
Made prompt try to focus back to last focused element

But it doesn't work on invisible element (e.g. the button only visible on hover/activate)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
tested 5/6/11/12 and all works

i'd like to suggest an better improvement on 6 though, now i focuses back on the create playlist button when u just created the playlist. I think its better to have the focus on the just created playlist.

**Comment by PikachuEXE** [comment]
> I think its better to have the focus on the just created playlist.

I tried calling `focus()` but it's not visible coz the default focus style (from vue/electron?) is for `:focus-visible`
- https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible
- https://trungk18.com/experience/focus-and-focus-visible/

But it's visible again with tab
As an alternative I can make it focus input again (1 more tab away)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hmm okay then i would like to focus it on the seachbar so i can tab to that just added playlist, because maybe that person added that playlist but dont want the video to be added in there so in that case they can still deselect the playlist

**Comment by PikachuEXE** [comment]
Done in https://github.com/PikachuEXE/FreeTube/commit/349c36377be49bbcefde5b1646d6168e5f65b69f

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM!

Edit: all accessibility issues related to playlists are solved. I'll keep this open so i can migrate this when playlists are implemented.

**Comment by PikachuEXE** [comment]
Updated `ft-list-video` to focus back on thumbnail link after add playlist prompt opened by add playlist button closed
But focus style is invisible due to `:focus-visible` (but tab works and add playlist button visible)
https://github.com/PikachuEXE/FreeTube/commit/1d41b23e91dd238eaf74ab44164f57c36540aa02

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Tested and looks like everything in this issue is addressed except for 4.1 but idk if something can be done about that

**Comment by PikachuEXE** [comment]
It's possible but might be a bit complicated
Kind of like preventing all other elements except top prompt from being tabbed
Which requires another level of changes and I won't do that in playlist branch (it's really about overall prompt implementation than just playlist)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
ok i'll leave it open so i know i need to migrate this over later

**Comment by PikachuEXE** [comment]
(10) should re-tested
Since thumbnail link now updated to be unselectable (idea from https://github.com/FreeTubeApp/FreeTube/pull/3954)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
10 lgtm!

**Comment by PikachuEXE** [comment]
4.1 partially fixed by having focus shifted to current prompt
But there is nothing preventing people pressing shift+tab to press cancel

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> 4.1 partially fixed by having focus shifted to current prompt But there is nothing preventing people pressing shift+tab to press cancel

LGTM, closing this issue.
