### ISSUE TITLE
[Feature Request]: Compiling issue list

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#44]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

I'll compile a list of what issues are being closed when this eventually gets merged just so u dont have to dig through the backlog :)

### Proposed Solution

- Closes https://github.com/FreeTubeApp/FreeTube/issues/3536
- Closes https://github.com/FreeTubeApp/FreeTube/issues/1762
- Closes https://github.com/FreeTubeApp/FreeTube/issues/1746
- Closes https://github.com/FreeTubeApp/FreeTube/issues/999
- Closes https://github.com/FreeTubeApp/FreeTube/issues/591
- Closes https://github.com/FreeTubeApp/FreeTube/issues/3613
- Closes https://github.com/FreeTubeApp/FreeTube/issues/2728

### Alternatives Considered

Listing everything here related to playlists in some way and maybe some issues are in there that maybe makes sense to be implemented/fixed in this repo:

1. https://github.com/FreeTubeApp/FreeTube/issues/3660
2. Has been moved to closes list ~https://github.com/FreeTubeApp/FreeTube/issues/3613~
3. https://github.com/FreeTubeApp/FreeTube/issues/3312
4. https://github.com/FreeTubeApp/FreeTube/issues/2939
5. https://github.com/FreeTubeApp/FreeTube/issues/2938
6. Has been moved to closes list ~https://github.com/FreeTubeApp/FreeTube/issues/2728~ 
7. https://github.com/FreeTubeApp/FreeTube/issues/2374
8. https://github.com/FreeTubeApp/FreeTube/issues/2333
9. https://github.com/FreeTubeApp/FreeTube/issues/2302
10. https://github.com/FreeTubeApp/FreeTube/issues/2274
11. https://github.com/FreeTubeApp/FreeTube/issues/2085
12. https://github.com/FreeTubeApp/FreeTube/issues/1826
13. https://github.com/FreeTubeApp/FreeTube/issues/1522
14. https://github.com/FreeTubeApp/FreeTube/issues/1426
15. https://github.com/FreeTubeApp/FreeTube/issues/1356
16. https://github.com/FreeTubeApp/FreeTube/issues/1103
17. https://github.com/FreeTubeApp/FreeTube/issues/1091
18. https://github.com/FreeTubeApp/FreeTube/issues/1016
19. https://github.com/FreeTubeApp/FreeTube/issues/643
20. https://github.com/FreeTubeApp/FreeTube/issues/547
21. https://github.com/FreeTubeApp/FreeTube/issues/519

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> [Import Playlists FreeTubeApp/FreeTube#1016](https://github.com/FreeTubeApp/FreeTube/issues/1016) might already be implemented but i have no YT account so there is no way for me to verify if an exported YT playlist works on import

@PikachuEXE is this implemented if so did u already tested it? Is it maybe possible for u to provide a YT exported playlist?

In addition to that i would like to test some edge cases like: 

- videos that are set to private in that playlist 
- videos that dont exist anymore
- shorts and previously streamed live videos
- Currently live videos (not sure if YT allows u to save that to a playlist)
- Upcoming videos or upcoming live videos (not sure if YT allows u to save that to a playlist)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PikachuEXE im energized to test stuff for u again so im here when u are ready to implement bunch of stuff again.

What issues from the list do you think should be addressed?

**Comment by PikachuEXE** [comment]
Which one(s) can be reproduced easily ._.
I can fix 1-3 cases a day maybe?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Well this one needs to be tested anyway https://github.com/PikachuEXE/FreeTube/issues/44#issuecomment-1595018633

But apart from that Nr 2, Nr 6 can be reproduced easy

**Comment by PikachuEXE** [comment]
Can you open a new issue just for YT playlist import?
Seems a lot to test/discuss (should not be put here anyway)

**Comment by PikachuEXE** [comment]
nr2 fixed
nr6 fixed but "Previous video" has no "loop enabled" check = it will visit last video regardless

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sorry for delay its been a busy week. Can confirm 2 is fixed but 6 is a bit strange.

i have 3 playlists, two playlists are working with the fix but the other one isnt. The two playlists that are working have low amount of vids in the < 12 and the playlist that isnt working has 100+ vids in them.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
update: i copied full WAN Show playlist and nr 6 worked fine so idk whats going on

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing this now that playlists v1 has dropped
