### ISSUE TITLE
[Bug]: Playlist with duplicate videos cannot be imported completely

### ISSUE THREAD

**Issue by PikachuEXE** [PikachuEXE/FreeTube#45]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

- Create a playlist
- Add duplicate videos to playlist
- Export
- Delete one of the duplicates (or more than one, just not all)
- Import

### Expected Behavior

There should be N videos (N=no. of videos before any video deletion) in the playlist

### Issue Labels

usability issue

### FreeTube Version

playlist branch

### Operating System Version

MacOS

### Installation Method

.dmg

### Primary API used

Local API

### Additional Information

After fixing #12 we allow adding a video (unique by `videoId`) more than once to a local playlist (well it seems possible for remote playlist to have duplicate videos too)

Current import logic find existing video in the existing playlist by `videoId` ONLY, forbidding any duplicate video entries to be imported

This bug does not affect playlist absent in local DB (it's will just add all video entries)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Fixed in https://github.com/PikachuEXE/FreeTube/commit/847f620af8f3c99b973a4f632cf3feae8164a265

@efb4f5ff-1298-471a-8973-3d47447115dc Please test when free :)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM!
