### ISSUE TITLE
[Bug]: Duplicate error

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#46]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Copy playlist A into playlist B (make sure u have some other random vids in there)
Go to playlist B

![Capture](https://github.com/PikachuEXE/FreeTube/assets/73130443/d52d5daa-1019-4623-8b2a-afd2b3d1a63e)

### Expected Behavior

idk

### Issue Labels

inconsistent behavior

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/847f620af8f3c99b973a4f632cf3feae8164a265

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Fixed in https://github.com/PikachuEXE/FreeTube/commit/3b1bace0231b38db7f8a6b455bfb9e097f38a202

But that also mean you should test https://github.com/PikachuEXE/FreeTube/issues/45 again with old/new exports

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Tested this, Retested #45 and both LGTM
