### ISSUE TITLE
[Bug]: pressing enter on creating new playlist name text field causes weird behavior

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#47]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Type in playlistname and press enter

https://github.com/PikachuEXE/FreeTube/assets/73130443/2a6fd995-ef33-4cd8-baa8-559990c33d4d

### Expected Behavior

umm i think this shouldnt happen so the user has to press on create button

### Issue Labels

inconsistent behavior

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/847f620af8f3c99b973a4f632cf3feae8164a265

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
It's so strange but I can't figure the reason of button click event triggered on close
So I can only come up with a workaround
https://github.com/PikachuEXE/FreeTube/commit/62418e91954cf01fefdaeb9189ed2ce58a8d113e

**Comment by PikachuEXE** [comment]
It's a `pointerEvent` but I just press enter 
I am so confused
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/064446ef-fe54-4e9f-8e31-f26969551ce5)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
workaround LGTM
