### ISSUE TITLE
[Feature Request]: Sort playlists

### ISSUE THREAD

**Issue by PikachuEXE** [PikachuEXE/FreeTube#48]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Cannot sort playlist in playlists view

### Proposed Solution

Add sort dropdown in playlists view
- A-Z
- Z-A
- Earliest created first
- Latest created first
- Earliest updated first
- Latest updated first (default)

### Alternatives Considered

![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/984db0f1-09d3-42d3-8e67-19a587426025)

### Issue Labels

improvement to existing feature

**Comment by PikachuEXE** [comment]
Implemented in https://github.com/PikachuEXE/FreeTube/commit/d1a2e90d1b797b3f18a20960e60e5d2148757c17

@efb4f5ff-1298-471a-8973-3d47447115dc help me test~

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Filter is visible when the user only has one playlist. Not very usefull to the user to show it if they cant use it. I would suggest showing the filter when user has more than 1 playlist

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Just created 3 playlist to set a baseline for the filters

- A-Z Linus,PSU,Tablet
- Z-A Tablet,PSU,Linus
- LC Tablet,PSU,Linus
- EC Linus,PSU,Tablet
- LU Tablet,PSU,Linus
- EU Linus,PSU,Tablet

https://github.com/PikachuEXE/FreeTube/assets/73130443/ad6ad06c-94d2-4c1e-84a6-3ed00440fa86

Changed playlist name

- A-Z Linus,PSU,Tablet
- Z-A Tablet,PSU,Linus
- **LC Linus,PSU,Tablet**
- EC Linus,PSU,Tablet
- LU Tablet,PSU,Linus
- EU Linus,PSU,Tablet

LC changed even though this has nothing to do with LC

https://github.com/PikachuEXE/FreeTube/assets/73130443/3e0b3dda-89b5-406d-9c25-7eab166fdf06

Removing a video in the playlist does not give it the first spot when sorted by latest updated

https://github.com/PikachuEXE/FreeTube/assets/73130443/c046d8ae-c50a-4f6a-b1af-7bea91ed8597

**Comment by PikachuEXE** [comment]
You makes me find a bug where the updates to playlists are not partial (but complete replace) when updating playlists
Which causes the created time to be absent later (in same window and DB)

Now should be all fixed

Details for nedb partial update op:
`$set` need to be used for simple documents as partial updates
I put the following code into https://npm.runkit.com/%40seald-io%2Fnedb to test:
```js
const Datastore = require("@seald-io/nedb")
const db = new Datastore()

await db.insertAsync({ _id: 1, videos: [], name: "111", lastUpdatedAt: 9999 })
console.log(await db.findAsync({ _id: 1 }))

await db.updateAsync({ _id: 1 }, { $set: { lastUpdatedAt: 8888 } }, { upsert: true })
console.log(await db.findAsync({ _id: 1 }))

await db.updateAsync({ _id: 2 }, { $set: { lastUpdatedAt: 8888 } }, { upsert: true })
console.log(await db.findAsync({ _id: 2 }))

await db.updateAsync({ _id: 1 }, { lastUpdatedAt: 8888 }, { upsert: true })
console.log(await db.findAsync({ _id: 1 }))

await db.updateAsync({ _id: 1 }, { _id: 1, lastUpdatedAt: 8888 }, { upsert: true })
console.log(await db.findAsync({ _id: 1 }))
```

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sorry for taking so long. That bug is indeed solved now.

- Could u address https://github.com/PikachuEXE/FreeTube/issues/48#issuecomment-1690113728 
- Also the naming naming latest and earliest throws me off a bit but i dont have a suggestions what might be a better fit

Random thought would be a nice to have to see the filters in the playlist view and maybe in add to playlist view

**Comment by PikachuEXE** [comment]
Forgot, see https://github.com/PikachuEXE/FreeTube/commit/69406b263f877bdcb92d05e859e3e53d61eae361 which changed logic for filter input AND sort select

Recently Created/Updated? (But what about Earliest...

> would be a nice to have to see the filters in the playlist view and maybe in add to playlist view

You mean... add filter in "add to playlist view"?
Edit: Wait there is a filter in "add to playlist view"
Edit 2: Do you mean sorting...?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Forgot, see [69406b2](https://github.com/PikachuEXE/FreeTube/commit/69406b263f877bdcb92d05e859e3e53d61eae361) which changed logic for filter input AND sort select

LGTM

> Recently Created/Updated? (But what about Earliest...

Recently Updated sounds better to me. Ugh idk what to do about earliest...

> > would be a nice to have to see the filters in the playlist view and maybe in add to playlist view
> 
> You mean... add filter in "add to playlist view"? Edit: Wait there is a filter in "add to playlist view" Edit 2: Do you mean sorting...?

Sorry for the confusion. It would be nice to also see the sort by in the following views


https://github.com/PikachuEXE/FreeTube/assets/73130443/c4cdea00-2062-438a-bba7-ba052e1373ab

**Comment by PikachuEXE** [comment]
- [Recently Created/Updated text applied](https://github.com/PikachuEXE/FreeTube/commit/f988fd8b676a5b70cfbabc845e1741c471691177)
- [Added sort options to add to playlist prompt](https://github.com/PikachuEXE/FreeTube/commit/433eb0d9768c962315f78824a47a86e484a37806)
- [Fixed sort order when filtered](https://github.com/PikachuEXE/FreeTube/commit/d6f2f5dd9ad8ae17a5f452709571e8040651536f)
- [Fix add to play prompt max width](https://github.com/PikachuEXE/FreeTube/commit/a2be3caedff1c360c091a0aaa3708684cb395a71)

**Comment by PikachuEXE** [comment]
(Not this issue related)
Also I just merged `development` into playlist branch
https://github.com/PikachuEXE/FreeTube/commit/4b21e75654c0779833abbd32b9eb368ba6f22f52

Let me know if you find any regression (I hope not

**Comment by PikachuEXE** [comment]
[Add playlists sort order for last played at (local playlists only)](4b21e75654c0779833abbd32b9eb368ba6f22f52)
New sort order used as default

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Will come back to this later today this will take me a bit longer to test!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> [Add playlists sort order for last played at (local playlists only)](4b21e75654c0779833abbd32b9eb368ba6f22f52) New sort order used as default

i think u meant to link https://github.com/PikachuEXE/FreeTube/commit/bdd002aee6de0cf8c349cc8c9daf3ee8349747c3

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> * [Recently Created/Updated text applied](https://github.com/PikachuEXE/FreeTube/commit/f988fd8b676a5b70cfbabc845e1741c471691177)

LGTM

> * [Added sort options to add to playlist prompt](https://github.com/PikachuEXE/FreeTube/commit/433eb0d9768c962315f78824a47a86e484a37806)

LGTM

> * [Fixed sort order when filtered](https://github.com/PikachuEXE/FreeTube/commit/d6f2f5dd9ad8ae17a5f452709571e8040651536f)

Everything seems to be sorted correctly so LGTM

> * [Fix add to play prompt max width](https://github.com/PikachuEXE/FreeTube/commit/a2be3caedff1c360c091a0aaa3708684cb395a71)

LGTM




> [Add playlists sort order for last played at (local playlists only)](4b21e75654c0779833abbd32b9eb368ba6f22f52) New sort order used as default

LGTM

> (Not this issue related) Also I just merged `development` into playlist branch [4b21e75](https://github.com/PikachuEXE/FreeTube/commit/4b21e75654c0779833abbd32b9eb368ba6f22f52)
> 
> Let me know if you find any regression (I hope not

I do not see anything weird so LGTM but if i do i'll let u know!


Could u also add the sort by dropdown when u go into one of your local playlist
I dont think most of the filters would fit on that page

the ones that will fit are

- A-Z (Video title)
- Z-A (Video title)
- A-Z (Channel name)
- Z-A (Channel name)
- Custom (Custom sorting will be set when user moves a video up/down in the list)
- Sorting by upload date of video (Recently uploaded / Earliest uploaded)
- Sort by views (Most viewed / Least Viewed)
- Sort by video length (Shortest somthing? / Longest somthing) 
- Sort by Recently added / Earliest added

**Comment by PikachuEXE** [comment]
I rather do it in v2...
Plus this is about sorting videos in playlist not sorting playlistssss

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> I rather do it in v2... Plus this is about sorting videos in playlist not sorting playlistssss

I think u mean the opposite. Im requesting sorting videos in playlist but this feature request is about sorting playlists. You're right that this isnt the right place to ask for it but im going to push back a little because i think that this is a very valuable thing to add in v1

**Comment by PikachuEXE** [comment]
> Plus this is about sorting videos in playlist not sorting playlistssss

For `this` I mean your request lol

I understand it's valuable but I don't guarantee implementing it in v1 and probably not in initial PR (nice to have, won't upset user too much if absent things) 

Anyway, put that into another issue

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sure, Everything in here LGTM so closing

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Oh lol this is your issue cant close

**Comment by PikachuEXE** [comment]
Oops
