### ISSUE TITLE
[Feature Request]: Get rid of the star save video icon

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#5]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

IMO the star icon that saves videos in the favorite playlist can be phased out. What if i dont want a favorite playlists? Now i have a empty playlist sitting there because the user sorts their vids properly because of the add to playlist button. Also if a user really want a fav playlist they can just create it now. No need for a shortcut (star save button) IMO.

### Proposed Solution

Get rid of the star save icon.

### Alternatives Considered

Maybe the better way to go is to replace it with a watch later icon and it will be a shortcut for that just like on YT

### Issue Labels

ease of use improvement

**Comment by PikachuEXE** [comment]
I am not sure if @PrestonN would agree to have the default lists to be removable
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/a17667d0-d2c5-4bc1-a743-d088c4de5a67)

Discuss in Matrix first?

**Comment by PikachuEXE** [comment]
Note: `Get rid of the star save icon` is fine for me, but not sure about `What if i dont want a favorite playlists?` part

**Comment by PikachuEXE** [comment]
Buttons removed via 
- https://github.com/FreeTubeApp/FreeTube/commit/d044dbb4cda8812bcdfbc2e98b58a779c11c61da
- https://github.com/FreeTubeApp/FreeTube/commit/721a7c7c7b21a03b399342734218c8fe5f36c8f4

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah sorry i wasnt clear enough of this one. 

- [x] 1. We should get rid of the star icon
- [x] 2. Legacy Favorites playlist should still exists so users can transfer their videos into other playlists
- [ ] 3. Favorites playlist should have an option to be deleted because im sure that there will be allot of users that will group their favorites into playlists they created. This will result into an empty favorites playlist that cant be deleted. 

Related note: Watch later playlist is added by default which is understandable but maybe we should give users the freedom to also delete that one if they dont want it

**Comment by PikachuEXE** [comment]
I am not sure what was the original plan for Watch later playlist
Maybe some custom function was planned
So I am not sure about that right now
I agree with making the Favorites playlist which is the old list deletable though (if no other special function tied to it)

**Comment by PikachuEXE** [comment]
But then making those default playlist deletable should be another issue ._.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sorry for not creating another issue and being a bit all over the place😅. Will do better! Closing as everything is implemented and LGTM
