### ISSUE TITLE
[Feature Request]: import non FT playlist(s)

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#50]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

We have to test if playlists imported from YT (and maybe newpipe?) will work in FT

### Proposed Solution

What we need:

An exported playlist from YT to test cases like:

- videos that are set to private in that playlist 
- videos that dont exist anymore
- shorts and previously streamed live videos
- Currently live videos (not sure if YT allows u to save that to a playlist)
- Upcoming videos or upcoming live videos (not sure if YT allows u to save that to a playlist)

### Alternatives Considered

None.

### Issue Labels

new feature

**Comment by PikachuEXE** [comment]
Need example files to test
And I can't find any playlist import related issue in main repo (maybe I used wrong keywords)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
From looking at https://github.com/PikachuEXE/FreeTube/issues/44 i can only find https://github.com/FreeTubeApp/FreeTube/issues/1016 but i cannot find example playlists with these usecases

**Comment by PikachuEXE** [comment]
My brain cached wrong info - It's already implemented and broken
Reality - NEVER been a thing

I am not including it in v1 (maybe v1.1, 2.0, etc.)

**Comment by PikachuEXE** [comment]
The YT playlist export is a list of CSV files ._.

Example (header text depends on user language I guess, maybe it can be forced via `hl=en`)
Headers: video ID, timestamp for video added to playlist time
```csv
影片 ID,播放清單影片的建立時間戳記
dKMTzrG92TE,2018-04-24T09:05:28+00:00

```

Update 1: Confirmed that https://takeout.google.com/?hl=en&pli=1 will export file with header text in `en`
```csv
Video ID,Playlist Video Creation Timestamp
dKMTzrG92TE,2018-04-24T09:05:28+00:00

```

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
migrated to main repo https://github.com/FreeTubeApp/FreeTube/issues/5057
