### ISSUE TITLE
[Bug]: playlist tab updates slow when big playlist is added

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#51]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Go to WAN Show playlist.
Load everything in playlist so u can copy every video in list
Copy playlist and add it to a new playlist
go to playlist tab and see that nr on playlist thumbnail does not represent amount of vids in playlist
wait a few seconds
see that nr gets updated

https://github.com/PikachuEXE/FreeTube/assets/73130443/f794e036-5623-4c5a-a676-b7e3a48214ca

### Expected Behavior

IDK if u can do something about this but would be nice to see the actual nr of vids faster

### Issue Labels

inconsistent behavior, visual bug

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/e0348a2758e503a1d7f9d772499b9a1f7c71bbf2

### Operating System Version

Ubuntu 22.04.1

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Done in https://github.com/PikachuEXE/FreeTube/commit/ca9816aec7cf589776ae67ec8d5c7c81602d03ac
But it's adding all videos at once, might appear slower / app unresponsive until all videos added

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM!
