### ISSUE TITLE
[Feature Request]: Remove `Remove watched videos` when there are no videos in playlist

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#52]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

1. Go to playlist tab
2. Create playlist
3. Go to the created playlist
4. See that the `Remove watched videos` button is available even though there are no videos in the list

### Proposed Solution

If no videos in playlist remove button

### Alternatives Considered

None.

### Issue Labels

ease of use improvement

**Comment by PikachuEXE** [comment]
[Done](https://github.com/PikachuEXE/FreeTube/commit/6aa8e3d81a6721d519593e18cda01ea6146b54c3)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM
