### ISSUE TITLE
[Bug]: Width of prompt looks weird

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#53]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

https://github.com/PikachuEXE/FreeTube/assets/73130443/ac1a2f54-ca27-43e2-9dbe-5d9c57ee40ee

### Expected Behavior

The right side of the prompt should look like the left side of the prompt

### Issue Labels

visual bug

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/ca0ac8ec43f13cb9d0522fc687e39e87e1d31914

### Operating System Version

Ubuntu 22.04.1

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
I tested with `autosize` but it looks crap
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/5f6395dd-ff20-48ab-b005-1396b70b32f2)

Otherwise it's a `development` issue (but not visible due to no existing prompt having this much content)

**Comment by PikachuEXE** [comment]
Spoke too soon
It's visible on open link prompt 
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/f3e219f0-f6a8-4b79-b4f8-c436471fd97e)

**Comment by PikachuEXE** [comment]
Oh wait it's from one of those changes from the old playlist branch...
Fixed in https://github.com/PikachuEXE/FreeTube/commit/402af7a2f885aed8e72c808aca844c97bff8a3f7
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/0e136d13-db90-402f-8e01-05848594d2b2)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM
