### ISSUE TITLE
[Feature Request]: Sort videos within playlist

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#54]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Sorting videos within the playlist isnt possible yet

### Proposed Solution

add the sort by dropdown when u go into one of your local playlist and add the following sorting options

- A-Z (Video title)
- Z-A (Video title)
- A-Z (Channel name)
- Z-A (Channel name)
- Custom (Custom sorting will be set when user moves a video up/down in the list)
- Sorting by upload date of video (Recently uploaded / Earliest uploaded)
- Sort by views (Most viewed / Least Viewed)
- Sort by video length (Shortest somthing? / Longest somthing) 
- Sort by Recently added / Earliest added

### Alternatives Considered

None.

### Issue Labels

new feature

**Comment by PikachuEXE** [comment]
But the sorting shouldn't affect the stored order right? (or the playing order)
Otherwise it will be way more complicated

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I agree but i think Custom will fulfill that if we use it by default

Edit: to clarify some more, when a playlist gets created and u add videos to it the default filter will always be Custom. If the user selects another filter that filter will be applied but if it is not to their liking they should be able to switch back to Custom and see their previously set Custom list. This way the user doesnt have to change the whole list again to their liking

**Comment by TrinityCryptx** [comment]
Want to add here that a playlist option would really be great for the FreeTube app.

Please add ASAP.

**Comment by profucius** [comment]
I'd like to mention that I would love this feature added. I use the playlists feature a lot, but with new videos being added always to the very bottom, with playlists over 100 videos, it takes a while to reach the newly added videos.

I do not need the playlist itself to be sorted per-se, but at least a sort of the view. Much like the sorting drop-down on the playlists page. I hope you'll consider this.

**Comment by tracure1337** [comment]
Just adding the link to the discussion on the 0.20.0 release.
https://github.com/FreeTubeApp/FreeTube/discussions/4848#discussioncomment-9013874

You will find 2 scripts to be able to divide and reverse the playlists. Please make backups before!

Any day  I will try to add a way to have OpenAI autosort all the videos into different categorized playlists.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
migrated to main repo https://github.com/FreeTubeApp/FreeTube/issues/4870
