### ISSUE TITLE
[Bug]: Legacy Favorites Broken Once Version with Playlists Is Ran

### ISSUE THREAD

**Issue by kommunarr** [PikachuEXE/FreeTube#58]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Download an RPM of this updated version and start it
2. Open an earlier version of FreeTube
3. Try to favorite/unfavorite a video. Encounter bug (nothing happening; existing favorites show up on videos in lists, but they cannot be unfavorited / other videos cannot be favorited)
4. Try to view Playlists tab; encounter bug (no favorites visible)

### Expected Behavior

On reverting to an earlier version of FreeTube, the favorites can be accessed as usual. This includes modifications to the Favorites playlist made in the new version. To not do so would cause massive uproar among people who have downloaded the newest version of FreeTube at any point but are deciding to use an older version.

Stopgap (worse) solution:
Allow for exporting Favorites playlist to legacy format that can be imported.

Dev discussion:
I haven't looked in depth into how this is implemented in this PR yet, but I'm presuming that we irreversibly wipe/reformat the Favorites DB upon loading up FreeTube for the first time with these changes present. This is overly destructive; we should either create a parallel DB that exists alongside legacy Favorites & is updated in unison, or keep the legacy Favorites system mostly unaltered.

### Issue Labels

data loss, feature stopped working, usability issue

### FreeTube Version

402af7a2f885aed8e72c808aca844c97bff8a3f7

### Operating System Version

OpenSUSE Tumbleweed

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Should be fixed by https://github.com/PikachuEXE/FreeTube/commit/ab5879ae46150d07303c92d0e4ea6e98071b4a5e
(Tested after switched back to dev version)
