### ISSUE TITLE
[Bug]: "Remove from watched" does not visually affect duplicates

### ISSUE THREAD

**Issue by kommunarr** [PikachuEXE/FreeTube#59]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Selecting "Remove from history" on dropdown options of a video only appears to affect one instance of it, even when there are multiple duplicates on a given view (e.g., a playlist). This is just visual and corrects when route is refreshed. Interestingly, the bug does not occur the other way with "Mark as Watched," which updates all duplicates instantaneously.

Replication steps:
1. Create playlist with two duplicates of watched video
2. In settings dropdown for one video on Playlist tab, click "Remove from watched". Encounter bug on other duplicate.

You can also replicate on any view with duplicate videos visible.

### Expected Behavior

All duplicates are visually removed from watched simultaneously, i.e. how "Mark as watched" works today.

### Issue Labels

visual bug

### FreeTube Version

125a467

### Operating System Version

OpenSUSE Tumbleweed

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
https://github.com/FreeTubeApp/FreeTube/pull/4017 might change behaviour (or not)
But no point checking this before it's merged

**Comment by PikachuEXE** [comment]
Playlist branch has merged https://github.com/FreeTubeApp/FreeTube/pull/4017 (from dev) and I tested once which seems fixed
Reopen if not

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
im late to the party but just wanted to confirm this is fixed

**Comment by PikachuEXE** [comment]
Test it ._.
