### ISSUE TITLE
[Bug]: Cant create playlist with the same name spelled different 

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#6]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

https://github.com/PikachuEXE/FreeTube/assets/73130443/5b4dcbdc-11e5-4f2b-a7dd-591ec78832d0

### Expected Behavior

I would like to create a playlist that has the same name but spelled differently

### Issue Labels

usability issue

### FreeTube Version

Your FT version

### Operating System Version

Win10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Fixed in https://github.com/FreeTubeApp/FreeTube/commit/150e7dabb63b6bc3c964c1feecc2615e56fb71f2

Another logic from old code

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm!
