### ISSUE TITLE
[Bug]: External player button should not be shown on local playlist

### ISSUE THREAD

**Issue by PikachuEXE** [PikachuEXE/FreeTube#60]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

- Enable external player
- View local playlist tab

### Expected Behavior

No external player button on local playlists

### Issue Labels

usability issue, visual bug

### FreeTube Version

https://github.com/PikachuEXE/FreeTube/commit/934b584355d778930fdb77f6df9b0b40859113ce

### Operating System Version

MacOS

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Should be fixed by https://github.com/PikachuEXE/FreeTube/commit/ca5f0455ad0440052b5a22ac6a67f4037fe1e126

**Comment by PikachuEXE** [comment]
Also fixed issue about video with local playlist in local playlist view & history view
https://github.com/PikachuEXE/FreeTube/commit/a3381cb501359741777cbbb29aa4c8cd974e487d
https://github.com/PikachuEXE/FreeTube/commit/db6e2bc9db7eb6737dfec7d04fae35c209e3222d

Update 1: another fix https://github.com/PikachuEXE/FreeTube/commit/2fd43b5108e8e9045107df7aecf04e1388ca6747

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Im not sure what External player button ur talking about

**Comment by PikachuEXE** [comment]
Open in external player button

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
i still see that button on hover?

**Comment by PikachuEXE** [comment]
The button for user playlist is hidden
But for video the external player should play the video without playlist (coz player would expect online playlist)

I can make the button hidden is confusing (but can almost be hidden in user playlist view, not history view)

**Comment by PikachuEXE** [comment]
Just made another fix https://github.com/PikachuEXE/FreeTube/commit/6e9636f4dd897713a01c255686dd4a429c52783c
Logic reversed ._.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ok im just being dumb but can u maybe make a screenshot of the button u have now hidden

**Comment by PikachuEXE** [comment]
OK, I am just too lazy to take screenshot until needed :P 

All local playlist list view - hidden
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/9a59f6b0-52cd-4c21-b7ed-e0e50e8f4e93)

Single local playlist view video - shown (and I am not sure if this should be shown or not :P)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/dee02574-9350-41f8-a606-3fc0aca1f0fe)

History view for video entry with last played with a local playlist - shown (definitely should be shown but without passing local playlist to external player)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/beff822e-8ab3-45fc-afb6-de78a4c439e2)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
im also not sure if it should be shown on NR 2 but if we choose for it to be hidden then it maybe also should be hidden on these 2 places 


https://github.com/PikachuEXE/FreeTube/assets/73130443/ba30ee3e-8f89-4055-b870-83a61fb91899

**Comment by PikachuEXE** [comment]
Leave it as is until more input available (I don't use external player at all...)
