### ISSUE TITLE
[Feature Request]: Remember last viewed entry on local playlist with duplicate videos

### ISSUE THREAD

**Issue by PikachuEXE** [PikachuEXE/FreeTube#61]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Similar to https://github.com/FreeTubeApp/FreeTube/pull/3006 but for user playlist with entries with duplicate videoIDs

Also see https://github.com/PikachuEXE/FreeTube/issues/57

### Proposed Solution

Remember the entry as well (not position)

### Alternatives Considered

Nein

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by PikachuEXE** [comment]
Done in https://github.com/PikachuEXE/FreeTube/commit/e2925427a04e18b0b1fcbcd33de97605440e2266

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM
