### ISSUE TITLE
[Feature Request]: Add search field to playlists

### ISSUE THREAD

**Issue by toby63** [PikachuEXE/FreeTube#64]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

As of now, I have one very big playlist and for me to be able to reorganize it, it would be nice to be able to search for videos inside it.

### Proposed Solution

Search field like in the old version, but also per playlist.

### Alternatives Considered

-

### Issue Labels

ease of use improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I think these should close this issue:

- https://github.com/FreeTubeApp/FreeTube/pull/4622
- https://github.com/FreeTubeApp/FreeTube/pull/4537

**Comment by toby63** [comment]
> I think these should close this issue:
> 
>     * [Add video search in user playlist feature FreeTubeApp/FreeTube#4622](https://github.com/FreeTubeApp/FreeTube/pull/4622)
> 
>     * [Add search playlists with matching videos function FreeTubeApp/FreeTube#4537](https://github.com/FreeTubeApp/FreeTube/pull/4537)

Yes, but only if it is also possible to search for videos in all playlists, instead of just per playlist.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Still debating if we should do something like that because it doesnt make sense to do that in the playlist view so the user can search for it again inside a playlist

**Comment by aleksejrs** [comment]
It does make sense: like global search vs narrowing down the search.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Resolved
