### ISSUE TITLE
[Feature Request]: Add "add to playlist" menu like firefox "quick" bookmarks

### ISSUE THREAD

**Issue by toby63** [PikachuEXE/FreeTube#65]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The way it works now I always have to choose a specific playlist that I want to add a video to.
But in Firefox for example the bookmarks work in a different way, this could be implemented here too, see below.

### Proposed Solution

In Firefox the latest bookmark folder is remembered, so if I click on the bookmark symbol in the url field once, the page/bookmark will simply be added to the last used folder.
If I want to change the folder, I can double-click on the bookmarks symbol.

Here you could implement a similar thing.
When I click on the "add-to-playlist"/save symbol, it could simply choose a standard playlist or the last used playlist and if I double-click on it, then it could open the more complex menu.

### Alternatives Considered

-

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @toby63 i think this is addressed.


https://github.com/PikachuEXE/FreeTube/assets/73130443/6520b1b2-ccf2-4e7e-9e32-c72e2ba2cf9c

**Comment by toby63** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Yes it is one way to implement something like that.
But this will surely need a bit more explanation, as I did not understand how this works, until I saw your video above.

Firefox quick bookmarks simply always uses the last chosen playlist though.

**Comment by aleksejrs** [comment]
@toby63 
> Firefox quick bookmarks simply always uses the last chosen playlist though.

I guess the bookmark folders were meant to be obsoleted by the AwesomeBar and tags though (seems like you can't search by folder name, but any of the other criteria can be selected), so it doesn't really matter where the bookmark ends up, and FreeTube doesn't have a global search or custom tags/descriptions.

**Comment by kommunarr** [comment]
I can understand this thinking, but this solution only works for bookmarks because they have one location. You would have to manually uncheck the previously added-to playlist and check the intended playlist whenever wanting to choose a different destination playlist. This problem is best solved by the quick bookmark system, batch selection / actions, and de-clunkifying the Add to Playlist UX.

**Comment by aleksejrs** [comment]
I guess I'd be happy with FreeTube using the last playlist if its name was next to the button. If it's the wrong list, the more important one should be recently used and near the top of the playlist popup.
And there should be a way to assign thumbnails/icons to lists, so they are not just from the first video (and different from what the thumbnail for that video is showing in the list).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> I can understand this thinking, but this solution only works for bookmarks because they have one location. You would have to manually uncheck the previously added-to playlist and check the intended playlist whenever wanting to choose a different destination playlist. 

Correction you dont have to first uncheck the playlist to then check another playlist to be your bookmark playlist. You can go directly to the playlist that you want as your quick bookmark list and check it.

> @efb4f5ff-1298-471a-8973-3d47447115dc Yes it is one way to implement something like that. But this will surely need a bit more explanation, as I did not understand how this works, until I saw your video above.

Documentation can always be added to make it clear to everyone how it is supposed to work. Also our implementation is similar to YT's one. They call their quick bookmarkable list Watch Later, we did the same but also gave the user the choice to change it whenever they want. Therefore imo this can be closed but waiting on other dev opinions.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> I can understand this thinking, but this solution only works for bookmarks because they have one location. You would have to manually uncheck the previously added-to playlist and check the intended playlist whenever wanting to choose a different destination playlist.
 
Correction you dont have to first uncheck the playlist to then check another playlist to be your bookmark playlist. You can go directly to the playlist that you want as your quick bookmark list and check it.
 
> @efb4f5ff-1298-471a-8973-3d47447115dc Yes it is one way to implement something like that. But this will surely need a bit more explanation, as I did not understand how this works, until I saw your video above.

Documentation can always be added to make it clear to everyone how it is supposed to work. Also our implementation is similar to YT's one. They call their quick bookmarkable list Watch Later, we did the same but also gave the user the choice to change it whenever they want. Therefore imo this can be closed but waiting on other dev opinions.

**Comment by kommunarr** [comment]
> > I can understand this thinking, but this solution only works for bookmarks because they have one location. You would have to manually uncheck the previously added-to playlist and check the intended playlist whenever wanting to choose a different destination playlist.
> 
> Correction you dont have to first uncheck the playlist to then check another playlist to be your bookmark playlist. You can go directly to the playlist that you want as your quick bookmark list and check it.

I'm talking about the proposal outlined in the OP, not the existing behavior.

**Comment by toby63** [comment]
I think that my proposal would make fast bookmarking a little easier, because imagine the following situation:
You are listening to music and you want to add several music videos to a specific music playlist.

Now your solution requires to set the music playlist as standard and then use the star symbol to add all the videos and then reset the standard or needing to go through the add-menu all the time.

My solution would not require that.
You would simply be able to use the last playlist chosen and then change the standard on the fly.

My proposal to have the best of both worlds would be:
1) A button to add videos to "watch later" or "sort later" (this could be a standard category)
2) a seperate button for quick bookmarks.

Either one or both of these could be also changed in your way (set a standard playlist), but if the user doesn't apply the setting, my proposed way would apply, see above.

**Comment by kommunarr** [comment]
That use case is (or, will be) covered by batch selection & actions pretty handily. https://github.com/FreeTubeApp/FreeTube/issues/2517

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This one doesnt need to be migrated to the main repo as there is already an issue and PR open to address the usecase like mentioned in the previous comment
