### ISSUE TITLE
[Feature Request]: Add an option to show all videos from all playlists

### ISSUE THREAD

**Issue by toby63** [PikachuEXE/FreeTube#66]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There are multiple problems with the New playlists:
1. You can't see all videos at once.
2. You can't search for videos.
3. You can't really sort videos intuitively
4. You can't see if a video was already added (#4561 fixes this partly, but in the add menu)

### Proposed Solution

Having an "All" Playlist can be the first way to solve this.

It would:
1. show all videos that were added to any list
2. maybe make it easier to search for specific videos, as it could be used as the only search source.
3. it could be the menu to sort videos, as it includes all videos.
4. make it easier to connect it with an indicator, such as the already existing star symbole.

### Alternatives Considered

-

### Issue Labels

improvement to existing feature

**Comment by toby63** [comment]
Closed in favor of https://github.com/FreeTubeApp/FreeTube/issues/4602.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@toby63 i know you're excited just as everyone else about this playlists feature, but could you please leave the issues open in this repo and not open them in the main one. 

Main reasons for this:

- I would rather not want to create allot of visibility on the playlist feature yet. Visibility will lead into more issues but we are still improving on the feature so those issues might already be solved by the time they're created. More issues will essentially lead to more overhead for us.
- I will do a proper migration of all these issues here when release comes around

Hopefully you dont take all this the wrong way, i know you have been around these parts for a very long time so the contributions you made are very valuable to us. These measures are just to prevent that the team will get an influx of issues from first time nightly build installers. In those kind of issues we mostly do allot of explaining and eventually close the issue but that can take a few days of going back and forth with those persons. This time can be better used for developing.

Are you ok with if we migrate the issue back to this repo?

**Comment by toby63** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 

I am ok with that.

I also want to apologize if I have created pressure or something like that, but I had the impression that things were going a bit into the wrong direction (with the new playlists) so I thought I might "intervene" early.
But now I realize that you implement the old features back in, step-by-step.

Also thank you for developing this and the new playlists, I think they are really useful.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There are multiple problems with the New playlists:
1. You can't see all videos at once.
2. You can't search for videos.
3. You can't really sort videos intuitively
4. You can't see if a video was already added (#4561 fixes this partly, but in the add menu)

### Proposed Solution

Having an "All" Playlist can be the first way to solve this.

It would:
1. show all videos that were added to any list
2. maybe make it easier to search for specific videos, as it could be used as the only search source.
3. it could be the menu to sort videos, as it includes all videos.
4. make it easier to connect it with an indicator, such as the already existing star symbole.

### Alternatives Considered

-

### Issue Labels

improvement to existing feature

### Additional Information

_No response_

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> You can't see if a video was already added (Update add video ot playlist prompt to show presence count when adding one video #4561 fixes this partly, but in the add menu)

As playlists are allowed to contain the same video multiple times, this would just have to be a visual indicator, not a toggle button like the old favorites.

Secondly as you can now create as many playlists as you want, I'm not sure how much benefit you would get from an icon that tells you it is added to a playlist, because you have no idea which one.

While an all playlist does sound cool, a playlist that will inevitably be gigantic, will cause significant performance problems. See https://github.com/FreeTubeApp/FreeTube/issues/4578 and https://github.com/FreeTubeApp/FreeTube/pull/4597 for more information (TL;DR freezing for 14 seconds, on decently powerful hardware, on the watch page and any time the video changes while you are in that playlist).

Therefore, anyone wanting to implement the all list, should definitely wait until there are workarounds in place for gigantic playlists, to avoid them causing performance problems (no that linked pull request doesn't solve it, solving it will require reworking the lazy loading system, which is a bigger change).

There is a difference between a user creating a gigantic playlist and it lagging versus FreeTube auto-generating that gigantic playlist for you. If FreeTube does it, everyone would have the reasonable expectation that it should work well, so the all list should definitely wait.

**Comment by toby63** [comment]
> Secondly as you can now create as many playlists as you want, I'm not sure how much benefit you would get from an icon that tells you it is added to a playlist, because you have no idea which one.

@absidue
But you would know that you already have marked the video as favorite.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Note to self: Migrating this and the other issues later. The most important ones have already been migrated over. You dont have to take any action so dont migrate them yourself :)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
After internal discussion we decided to not migrate this over.

**Comment by toby63** [comment]
> After internal discussion we decided to not migrate this over.

Well I of course have to accept your decision, but even if you never want to implement this (which I think is 1. too early to say and 2. a big mistake (because of the multiple things that this could "solve"), it would be better to migrate this, so that people who want this feature can find this issue and see that you don't want to implement this, instead of opening new issues etc.
