### ISSUE TITLE
[Feature Request]: Edit playlists with multi select

### ISSUE THREAD

**Issue by toby63** [PikachuEXE/FreeTube#67]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When you have very large lists, it can be useful to be able to select multiple entries and then move them at once.

### Proposed Solution

Offer a "select box" in the left corner of a video entry for example and then you can select one or multiple videos this way and then click on seperate buttons (in the left menu e.g. or in the right-click menu) to move the videos or add them to another playlist etc.

### Alternatives Considered

-

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@jasonhenriquez would something like this be addressed by https://github.com/FreeTubeApp/FreeTube/pull/4198?

**Comment by kommunarr** [comment]
Yep! I'll update the PR description now.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing this as all the issues will be closed in this repo. Im not going to migrate this issue though because there is already a PR open for this. If there is anything you like to add you can comment on there :)
