### ISSUE TITLE
[Feature Request]: display playlist contents as grid

### ISSUE THREAD

**Issue by toby63** [PikachuEXE/FreeTube#68]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Right now I only see a top-down list.

### Proposed Solution

Offer different options, mainly a grid view.

Additional views could be:
- show only titles
- left-to-right list instead of top-down

### Alternatives Considered

-

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Good point this was also brought up in our dev chat by @jasonhenriquez. I do like to add that normal playlists are also not viewable in a grid though.

**Comment by kommunarr** [comment]
I think that's fair, but it's also worth noting that I think it's fine if user playlists have different styling choices and capabilities than remote playlists.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
being tracked in https://github.com/FreeTubeApp/FreeTube/issues/4708
