### ISSUE TITLE
[Bug]: Search field in playlist menu only searches for playlist titles (it seems)

### ISSUE THREAD

**Issue by toby63** [PikachuEXE/FreeTube#69]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. I go to the playlists menu.
2. I type in something in the search field.
3. I click enter.
4. It shows no results or only results that match a playlist title.

### Expected Behavior

I would expect the search would...well...search for the content inside the playlists as well.

### Issue Labels

feature stopped working, usability issue

### FreeTube Version

recent

### Operating System Version

Manjaro

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Additional Information

I don't know if this is even a bug, maybe it's also a "feature", but I would like to ask for changing this.

I see two options for it:
1. Show playlist results first and Content/Video results second.
2. Add options next to the search field, to select whether the user wants to search for playlist titles or videos.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is expected behavior.
