### ISSUE TITLE
[Feature Request]: Add videos to playlist from video page

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#7]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

There is no way to add a video to a certain playlist right now

![Capture](https://github.com/PikachuEXE/FreeTube/assets/73130443/334e4146-1ab1-4e13-848a-92cff31ad529)

### Proposed Solution

Allow videos to be saved to playlist from the video page

### Alternatives Considered

None.

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by PikachuEXE** [comment]
Added in https://github.com/FreeTubeApp/FreeTube/commit/fc1cb33ce3c66dfbdfd105e11bf0dc01d51f067d

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm. Pikachu FTW!
