### ISSUE TITLE
[Feature Request]: Auto-play option for playlists should be seperated between Youtube playlists and local playlists

### ISSUE THREAD

**Issue by toby63** [PikachuEXE/FreeTube#70]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

It seems that the local playlists also have auto-play enabled when the option is active.

### Proposed Solution

I think there should be an additional seperate option for local playlists, because at least I would like to disable it for local playlists, but enable it for youtube playlists.

### Alternatives Considered

-

### Issue Labels

new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Doesn't this feature fulfill that usecase?

https://github.com/PikachuEXE/FreeTube/assets/73130443/01ea9764-8d3e-4c5d-afe1-0d60a586c297


Edit: Oh lol nvm that doesnt fulfill the usecase because the user has to enable this on every vid

**Comment by toby63** [comment]
Well the problem is that I would like to:
1. Have autoplay enabled for regular playlists on Youtube, e.g. OST from Game XY.
2. have autoplay disabled for the local playlists in FreeTube that I created myself.

Last time I checked these options were combined and they should IMHO be seperate.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Summoning @jasonhenriquez for thoughts if something like this make sense to implement

**Comment by kommunarr** [comment]
It makes sense to me as a user because I use Favorites as a grab bag, but remote playlists are generally intended to be episodic and/or binged. That's pretty specific / contextual to the way that I use things, though, so I dunno.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We can maybe just show an autoplay toggle and let the user decide what to do with it, doesnt matter what kind of playlist. So if user decides to togglle it for remote it will be enabled until user decides to turn it off. If user decides to watch a local created playlist and autoplay is enabled, they only have to disable it once.

Just like how our autoplay works at the moment when you're watching normal vids

**Comment by kommunarr** [comment]
Yeah, I agree, this is probably better handled by [an inline autoplay toggle in the media player.](https://github.com/FreeTubeApp/FreeTube/issues/1181#issuecomment-1829194576) Only minor implementation note I have to add is that it should set both playlist autoplay and regular autoplay to disabled when disabled while watching a playlist.

**Comment by toby63** [comment]
> We can maybe just show an autoplay toggle and let the user decide what to do with it, doesnt matter what kind of playlist. So if user decides to togglle it for remote it will be enabled until user decides to turn it off. If user decides to watch a local created playlist and autoplay is enabled, they only have to disable it once.
> 
> Just like how our autoplay works at the moment when you're watching normal vids

I don't know if I understand that correctly, but if the global setting ist changed via a toggle in every video, I don't like that.
I would like to be able to set a standard and this standard is always used, and then I can enable/disable autoplay on a case-to-case basis.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing as this can be solved by implementing https://github.com/FreeTubeApp/FreeTube/issues/1181 and https://github.com/FreeTubeApp/FreeTube/issues/2295

**Comment by toby63** [comment]
> Closing as this can be solved by implementing [FreeTubeApp#1181](https://github.com/FreeTubeApp/FreeTube/issues/1181) and [FreeTubeApp#2295](https://github.com/FreeTubeApp/FreeTube/issues/2295)

Not really as that would mean that I have to set things every time, but I would like to set things once for these types of playlists.

**Comment by kommunarr** [comment]
I would add on #1996 as an alternative as well. The idea for this one is that there are arbitrarily many different contexts in which someone would want a setting enabled versus disabled. Instead of having multiple different sub-settings per any possible context, the user can switch to a profile for their preferred viewing context.
