### ISSUE TITLE
[Feature Request]: Play random video

### ISSUE THREAD

**Issue by toby63** [PikachuEXE/FreeTube#71]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

As local playlists might have a different purpose than usual youtube playlists, it might be a good idea to be able to play random videos inside of a playlist.

### Proposed Solution

Add two buttons:
- One that plays only one random video
- and one that plays random videos until stopped

### Alternatives Considered

-

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
When the user is watching a playlist they can just hit the shuffle button at any time. I dont see any added value to adding this to the inside playlist view

**Comment by toby63** [comment]
Ah yes, thats correct (I admit that I didn't think about this option in relation to the local playlists), but still an additional button would be useful IMHO.

1. On the playlist page: It is easier to simply be able to click a button, instead of having to click on a specific video, then activate shuffle and then click on next video.
2. Inside the small playlist view: It would also be useful to be able to just load a random video from there too.
