### ISSUE TITLE
[Bug]: Run failed: Project Board Automation - development (5a316f1)

### ISSUE THREAD

**Issue by toby63** [PikachuEXE/FreeTube#72]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

GitHub Problem:

Each time I create an issue here, i get an email about a failed automation.
I assume that you created an automated sorting of issues, that fails.

Details:
```
View results: https://github.com/PikachuEXE/FreeTube/actions/runs/8411748633

Jobs:
  * assign-issues-to-projects failed (1 annotation)
```

### Expected Behavior

No fail.

### Issue Labels

feature stopped working

### FreeTube Version

-

### Operating System Version

-

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Contents from the Project boards dont get carried over in forks. Thats why you get that error.
