### ISSUE TITLE
[Feature Request]: Make playlist button colors based on 2nd theme color

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#8]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Dont get me wrong i really like that it was based on the main theme color but all the buttons in the UI are based one the 2nd theme color and it feels off IMO to divert to that

### Proposed Solution

Make playlist button colors based on 2nd theme color

### Alternatives Considered

None.

### Issue Labels

visual improvement

**Comment by PikachuEXE** [comment]
I need a screenshot to confirm which buttons you are talking about...
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/d3876c98-d32e-4979-8f2d-4287df5ec27b)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/0ee22067-df5c-4db3-b522-f34b7a4de456)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/92677de8-c282-43d9-bdc0-85c91788c9e9)

I have no idea I just use existing code from old branch :S

**Comment by PikachuEXE** [comment]
I am guessing the following is the intended effect?
Will commit after getting confirmation
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/26cad591-ce22-44f6-a0c5-4fa23060e3e0)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/14051b03-ad6a-4e44-bcd8-c6d201188eb1)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Yes i was talking about those buttons. Following 2 should also be altered.

This create new playlist button on the playlist home page
![playlist-home-page-add-playlist-button](https://github.com/PikachuEXE/FreeTube/assets/73130443/98ab69dc-06dc-4020-a703-abc94eb3233b)

This copy playlist button when u navigate to a random playlist on a channel

![random-playlist-copy-playlist-button](https://github.com/PikachuEXE/FreeTube/assets/73130443/55cd5bfe-bfe2-4efd-9a93-1d0d68864f81)

**Comment by PikachuEXE** [comment]
Updated in https://github.com/FreeTubeApp/FreeTube/commit/9b07891be3ad4a9fb1ae49ed4906dc9605c1e7cb

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
lgtm
