### ISSUE TITLE
[Bug]: Moving or removing a video from playlist isnt nice to watch

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#9]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

IMO It doesnt look very great to me when a video gets moved or removed

https://github.com/PikachuEXE/FreeTube/assets/73130443/50f383e1-7fce-4760-82be-3492d88dbcdd

### Expected Behavior

A smooth like way to see the video moved or removed

### Issue Labels

visual bug

### FreeTube Version

Your FT version

### Operating System Version

Win10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Sliding effect?
There is no example to copy :S

**Comment by PikachuEXE** [comment]
Like this?

https://github.com/PikachuEXE/FreeTube/assets/1018543/7d0a362b-3400-4f65-88f5-c6de015d7403

**Comment by PikachuEXE** [comment]
Added one in https://github.com/FreeTubeApp/FreeTube/commit/f46843aaad47db36b2ed0d73b1446c010c289a2c
Test yourself

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Damn i really like what u did here, LV(very)GTM!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PikachuEXE is this stutter behavior near the end of the video fixable?

https://github.com/PikachuEXE/FreeTube/assets/73130443/ecb29dc7-7186-49fe-8267-635537e8b23a

**Comment by PikachuEXE** [comment]
I think it's just CSS transition not played nicely?
You can try to adjust the properties and see if anything can fix it, but the animation is played=implemented by the browser/electron in the end

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
tbh it lgtm if i'm really annoyed about i i'll open up an issue for it but this implementation is way better than what it was before. 

Good job Pikachu have an 


![Thunder_Stone_anime](https://github.com/PikachuEXE/FreeTube/assets/73130443/1d91367c-7049-4daa-aa06-4a72f9fdbf48)

**Comment by PikachuEXE** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
(Press B)
